// Generated by build.js — do not edit
const SITE_ARTICLES = [
  {
    "slug": "2026-07-04-china-auto-daily",
    "date": "2026-07-04",
    "title_en": "BYD, Geely Hit Export Records in June as XPeng Takes Mona L03 to 64 Markets",
    "title_zh": "比亚迪、吉利6月出口双双破纪录，小鹏Mona L03剑指全球64国",
    "excerpt_en": "BYD's June overseas deliveries hit an all-time high of 175,349 units (+94.7%), Geely first crossed 100,000 monthly exports (+157%), and XPeng will globally launch the Mona L03 in Munich on July 16 across 64 markets.",
    "excerpt_zh": "比亚迪6月海外交付17.53万辆创历史新高（+94.7%），吉利首破月度出口10万辆大关（+157%），小鹏Mona L03将于7月16日在慕尼黑向全球64国同步上市。",
    "tag_en": "Daily Briefing",
    "tag_zh": "每日简报"
  }
];
