// Generated by build.js — do not edit
const SITE_ARTICLES = [
  {
    "slug": "2026-07-06-china-auto-daily",
    "date": "2026-07-06",
    "title_en": "BYD Hits 792K Overseas H1, XPeng Debuts in Munich, GAC Exports Surge 132%",
    "title_zh": "BYD上半年海外销量达79.2万辆，小鹏慕尼黑首发，广汽出口增132%",
    "excerpt_en": "Chinese automakers logged a historic overseas half-year in 2026: BYD's H1 exports hit 792,256 units (+70.7%), GAC surged 132%, and XPeng chose Munich—not Beijing—for the Mona L03 world premiere.",
    "excerpt_zh": "2026年上半年中国车企出海创历史：BYD海外销量达79.2万辆（+70.7%），广汽出口激增132%，小鹏选择慕尼黑而非北京作为Mona L03全球首发地。",
    "tag_en": "Daily Briefing",
    "tag_zh": "每日简报"
  },
  {
    "slug": "why-chinese-automakers-are-expanding-faster-overseas",
    "date": "2026-07-05",
    "title_en": "Why Chinese Automakers Are Expanding Faster Overseas",
    "title_zh": "中国车企为什么在海外越跑越快",
    "excerpt_en": "Price war at home, fatter margins abroad, and a closing tariff window: the three forces pushing every major Chinese automaker to accelerate globalization at the same time.",
    "excerpt_zh": "国内价格战、海外高毛利、正在关闭的关税窗口：三股力量让所有主要中国车企同时踩下全球化油门。",
    "tag_en": "Analysis",
    "tag_zh": "分析"
  },
  {
    "slug": "why-chinese-automakers-are-building-overseas-plants",
    "date": "2026-07-05",
    "title_en": "Why Chinese Automakers Are Building Overseas Plants",
    "title_zh": "中国车企为什么在海外建厂",
    "excerpt_en": "From Thailand to Hungary to Brazil, Chinese automakers are racing to manufacture where they sell. The logic: get inside the tariff wall before it rises further.",
    "excerpt_zh": "从泰国到匈牙利再到巴西，中国车企正在赶工\"销地制造\"。逻辑只有一条：赶在关税墙进一步抬高前进到墙内。",
    "tag_en": "Exports",
    "tag_zh": "出口"
  },
  {
    "slug": "geely-global-brand-portfolio-explained",
    "date": "2026-07-05",
    "title_en": "Geely's Global Brand Portfolio Explained",
    "title_zh": "一文看懂吉利的全球品牌矩阵",
    "excerpt_en": "Volvo, Polestar, Lotus, Zeekr, Lynk & Co, Proton, the Galaxy line — no Chinese group globalized through ownership like Geely. Here is how the pieces fit, and why exports just hit a record.",
    "excerpt_zh": "沃尔沃、极星、路特斯、极氪、领克、宝腾、银河——没有哪家中国集团像吉利这样靠股权完成全球化。本文拆解各块拼图，以及出口为何刚创纪录。",
    "tag_en": "Analysis",
    "tag_zh": "分析"
  },
  {
    "slug": "chinese-evs-in-europe-opportunity-tariffs-and-competition",
    "date": "2026-07-05",
    "title_en": "Chinese EVs in Europe: Opportunity, Tariffs and Competition",
    "title_zh": "中国电动车在欧洲：机会、关税与竞争",
    "excerpt_en": "Europe is the hardest market Chinese EV makers have entered — and the one they refuse to give up. Tariffs reshaped the strategy from exporting cars to building them inside the wall.",
    "excerpt_zh": "欧洲是中国电动车企进入过的最难市场，也是它们拒绝放弃的市场。关税把战略从\"出口整车\"改写为\"墙内造车\"。",
    "tag_en": "Markets",
    "tag_zh": "市场"
  },
  {
    "slug": "chinese-cars-in-the-middle-east-why-demand-is-rising",
    "date": "2026-07-05",
    "title_en": "Chinese Cars in the Middle East: Why Demand Is Rising",
    "title_zh": "中国汽车在中东：需求为什么在上升",
    "excerpt_en": "The Gulf went from skeptical to one of the fastest-adopting regions for Chinese cars in five years. Petrol SUVs opened the door; EVs and flagship showrooms are walking through it.",
    "excerpt_zh": "五年之间，海湾从怀疑者变成中国汽车渗透最快的区域之一。燃油 SUV 敲开了门，电动车和旗舰展厅正鱼贯而入。",
    "tag_en": "Markets",
    "tag_zh": "市场"
  },
  {
    "slug": "chinese-cars-in-africa-suvs-pickups-and-commercial-vehicles",
    "date": "2026-07-05",
    "title_en": "Chinese Cars in Africa: SUVs, Pickups and Commercial Vehicles",
    "title_zh": "中国汽车在非洲：SUV、皮卡与商用车",
    "excerpt_en": "Africa is the quietest front of China auto globalization — and possibly the most durable. The wedge is not EVs but affordable SUVs, working pickups and commercial vehicles, with local assembly starting to take root.",
    "excerpt_zh": "非洲是中国汽车全球化最安静的战线,也可能是最持久的一条。楔子不是电动车,而是平价 SUV、能干活的皮卡和商用车——本地组装也开始扎根。",
    "tag_en": "Markets",
    "tag_zh": "市场"
  },
  {
    "slug": "chinas-car-exports-why-global-markets-are-paying-attention",
    "date": "2026-07-05",
    "title_en": "China's Car Exports: Why Global Markets Are Paying Attention",
    "title_zh": "中国汽车出口：全球市场为何开始认真对待",
    "excerpt_en": "China has been the world's largest car exporter for three straight years, and the first half of 2026 shows the machine accelerating: record brand-level shipments, overseas plants multiplying, and exports becoming the industry's profit engine.",
    "excerpt_zh": "中国已连续三年蝉联全球第一大汽车出口国，2026 年上半年这台机器仍在加速：品牌出口纪录、海外工厂遍地开花、出口成为行业利润引擎。",
    "tag_en": "Analysis",
    "tag_zh": "分析"
  },
  {
    "slug": "china-auto-export-data-what-global-dealers-should-watch",
    "date": "2026-07-05",
    "title_en": "China Auto Export Data: What Global Dealers Should Watch",
    "title_zh": "中国汽车出口数据：全球经销商应该盯哪些指标",
    "excerpt_en": "Wholesale vs retail, exports vs overseas sales, customs vs association data — China auto numbers confuse even professionals. A practical guide to reading them, and the five indicators that matter most.",
    "excerpt_zh": "批发与零售、出口与海外销量、海关与协会口径——中国汽车数据连专业人士都会看混。这是一份实用的阅读指南,以及最值得盯的五个指标。",
    "tag_en": "Data",
    "tag_zh": "数据"
  },
  {
    "slug": "chery-overseas-growth-why-emerging-markets-matter",
    "date": "2026-07-05",
    "title_en": "Chery's Overseas Growth: Why Emerging Markets Matter",
    "title_zh": "奇瑞的海外增长：新兴市场为什么是胜负手",
    "excerpt_en": "China's export champion for 23 straight years built its lead the unfashionable way: petrol SUVs, emerging markets, and local assembly — long before the EV wave. Now that base is funding a push into Europe.",
    "excerpt_zh": "连续 23 年的中国出口冠军用最不时髦的方式建立领先：燃油 SUV、新兴市场、本地组装——远早于电动车浪潮。如今这个基本盘正在为进军欧洲输血。",
    "tag_en": "Analysis",
    "tag_zh": "分析"
  },
  {
    "slug": "byd-global-expansion-strategy-key-markets-to-watch",
    "date": "2026-07-05",
    "title_en": "BYD's Global Expansion Strategy: Key Markets to Watch",
    "title_zh": "比亚迪全球扩张战略：值得盯住的关键市场",
    "excerpt_en": "BYD went from exporting almost nothing in 2021 to targeting 1.5 million overseas sales in 2026. Its strategy rests on three pillars: ships, plants, and a product ladder from the Seagull to Yangwang.",
    "excerpt_zh": "比亚迪从 2021 年几乎零出口，到 2026 年瞄准 150 万辆海外销量。它的战略立于三根支柱：船队、工厂，和从海鸥到仰望的产品阶梯。",
    "tag_en": "Analysis",
    "tag_zh": "分析"
  },
  {
    "slug": "2026-07-05-china-auto-daily",
    "date": "2026-07-05",
    "title_en": "BYD Hits 792K Overseas in H1, Geely Breaks 100K Monthly, XPeng Goes to Munich",
    "title_zh": "比亚迪上半年海外79万辆、吉利单月破10万、小鹏赴慕尼黑全球首发",
    "excerpt_en": "BYD delivered 792,256 vehicles overseas in H1 2026 (+70.7%), Geely crossed 100K monthly exports for the first time, and XPeng will globally launch the Mona L03 in Munich on July 16 across 64 countries.",
    "excerpt_zh": "比亚迪2026年上半年海外交付79.23万辆（+70.7%），吉利6月出口首破10万辆，小鹏Mona L03定于7月16日在慕尼黑向64国同步全球首发。",
    "tag_en": "Daily Briefing",
    "tag_zh": "每日简报"
  },
  {
    "slug": "2026-07-04-china-auto-daily",
    "date": "2026-07-04",
    "title_en": "BYD, Geely Hit Export Records in June as XPeng Takes Mona L03 to 64 Markets",
    "title_zh": "比亚迪、吉利6月出口双双破纪录，小鹏Mona L03剑指全球64国",
    "excerpt_en": "BYD's June overseas deliveries hit an all-time high of 175,349 units (+94.7%), Geely first crossed 100,000 monthly exports (+157%), and XPeng will globally launch the Mona L03 in Munich on July 16 across 64 markets.",
    "excerpt_zh": "比亚迪6月海外交付17.53万辆创历史新高（+94.7%），吉利首破月度出口10万辆大关（+157%），小鹏Mona L03将于7月16日在慕尼黑向全球64国同步上市。",
    "tag_en": "Daily Briefing",
    "tag_zh": "每日简报"
  }
];
