#!/usr/bin/env node
// ============ STATIC PRERENDER ============
// Generates one fully-rendered HTML file per route so search engines see real
// content at real URLs. Run after editing js/data.js or js/i18n.js:
//   node build.js
// Output: index.html, brands.html, models.html, news.html, tech.html,
//         about.html, 404.html  (Vercel cleanUrls serves /brands from brands.html)

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = __dirname;
const SITE = 'https://www.topchinacar.com';
const BUILD_V = new Date().toISOString().slice(0, 16).replace(/[-:T]/g, ''); // cache-busting version

// ---- Collect daily articles (articles/*.json, written by the GCP pipeline) ----
const ARTICLES_DIR = path.join(ROOT, 'articles');
let articles = [];
if (fs.existsSync(ARTICLES_DIR)) {
  articles = fs.readdirSync(ARTICLES_DIR)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      try { return JSON.parse(fs.readFileSync(path.join(ARTICLES_DIR, f), 'utf-8')); }
      catch (e) { console.error(`✗ skipping bad article ${f}: ${e.message}`); return null; }
    })
    .filter(a => a && a.slug && a.date && a.title_en && a.html_en)
    .sort((a, b) => b.date.localeCompare(a.date) || b.slug.localeCompare(a.slug));
}

// Lightweight index (no article bodies) shared with the client for the News page
const articlesIndex = articles.map(a => ({
  slug: a.slug, date: a.date,
  title_en: a.title_en, title_zh: a.title_zh || a.title_en,
  excerpt_en: a.excerpt_en || '', excerpt_zh: a.excerpt_zh || a.excerpt_en || '',
  tag_en: a.tag_en || 'Daily Briefing', tag_zh: a.tag_zh || '每日简报'
}));
fs.writeFileSync(path.join(ROOT, 'js', 'articles-data.js'),
  '// Generated by build.js — do not edit\nconst SITE_ARTICLES = '
  + JSON.stringify(articlesIndex, null, 2) + ';\n');

// ---- Load site scripts in a sandbox with a minimal document stub ----
const sandbox = {
  document: { documentElement: { lang: 'en' } },
  module: undefined,
  console
};
vm.createContext(sandbox);
for (const f of ['js/data.js', 'js/i18n.js', 'js/articles-data.js', 'js/pages.js']) {
  vm.runInContext(fs.readFileSync(path.join(ROOT, f), 'utf-8'), sandbox, { filename: f });
}
const PAGE_ROUTES = vm.runInContext('PAGE_ROUTES', sandbox);

// Feature story bodies (build-time only — never shipped to the client)
let SITE_STORIES = [];
if (fs.existsSync(path.join(ROOT, 'js', 'stories-data.js'))) {
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'js', 'stories-data.js'), 'utf-8'), sandbox, { filename: 'js/stories-data.js' });
  SITE_STORIES = vm.runInContext('typeof SITE_STORIES !== "undefined" ? SITE_STORIES : []', sandbox);
}

// ---- Per-page metadata ----
const PAGES = {
  '/': {
    file: 'index.html',
    title: 'TopChinaCar — The New Era of Chinese Automobiles',
    desc: 'An editorial guide to Chinese automobiles for overseas readers: BYD, Xiaomi, NIO, Xpeng, Zeekr, Geely — brands, models, technology and the EV revolution reshaping the global auto industry.'
  },
  '/brands': {
    file: 'brands.html',
    title: 'Chinese Car Brands: The Complete Index — BYD, Geely, NIO & 27 More | TopChinaCar',
    desc: 'A field guide to 30 Chinese automakers: legacy groups (BYD, Geely, SAIC, Chery, Great Wall, Dongfeng), EV startups (NIO, Xpeng, Li Auto, Xiaomi, Leapmotor) and their sub-brands — founding dates, HQ, focus and export footprint.'
  },
  '/models': {
    file: 'models.html',
    title: 'Featured Chinese EV Models — Range, Price & Specs | TopChinaCar',
    desc: 'The Chinese EVs defining the new era: BYD Seal, Xiaomi SU7 Ultra, NIO ET9, Xpeng G6, Li Auto MEGA, Zeekr 001 — with real range figures, 0-100 times and prices in ¥/$/€.'
  },
  '/news': {
    file: 'news.html',
    title: 'China Auto Export & EV Industry News | TopChinaCar',
    desc: 'Curated reporting on Chinese car exports, new model launches, battery technology and policy — plus the weekly China Export Watch column.'
  },
  '/tech': {
    file: 'tech.html',
    title: 'Chinese EV Technology Explained: 800V, City Autonomy, Blade Batteries | TopChinaCar',
    desc: 'Deep dives into the technologies behind China\'s automotive lead: 800V high-voltage platforms, city-level autonomous driving, smart cockpits, and Blade & CTB batteries.'
  },
  '/about': {
    file: 'about.html',
    title: 'About TopChinaCar — Independent Editorial on Chinese Automakers',
    desc: 'TopChinaCar is an independent, bilingual editorial publication explaining Chinese automobiles to overseas readers — brands, cars, technology and people. No hype, no dismissal.'
  },
  '/quote': {
    file: 'quote.html',
    title: 'Import Chinese Cars — Export & Wholesale Quotes for Dealers | TopChinaCar',
    desc: 'Dealer, fleet and importer inquiries for Chinese vehicles: BYD, Chery, Geely, MG and more. Tell us your market, models and volume — FOB/CIF quotes through licensed Chinese exporters within 48 hours.'
  }
};

const NAV = [
  ['/', 'nav.home', 'Home'],
  ['/brands', 'nav.brands', 'Brands'],
  ['/models', 'nav.models', 'Models'],
  ['/news', 'nav.news', 'News'],
  ['/tech', 'nav.tech', 'Tech'],
  ['/about', 'nav.about', 'About'],
  ['/quote', 'nav.quote', 'Get a Quote']
];

function headerHTML(route) {
  const navLinks = NAV.map(([href, key, label]) =>
    `<a href="${href}"${href === route ? ' class="active"' : ''} data-i18n="${key}">${label}</a>`).join('\n      ');
  return `<header class="site-header" id="siteHeader">
  <div class="container header-inner">
    <a href="/" class="logo" aria-label="TopChinaCar home">
      <svg width="28" height="28" viewBox="0 0 32 32" fill="none" aria-hidden="true">
        <rect width="32" height="32" rx="2" fill="currentColor"/>
        <text x="16" y="23" font-family="Playfair Display,serif" font-size="22" font-weight="900" text-anchor="middle" fill="#d4302a">T</text>
      </svg>
      <span class="logo-text">
        <span class="logo-main">TopChinaCar</span>
        <span class="logo-sub" data-i18n="logo.sub">The New Era of Chinese Automobiles</span>
      </span>
    </a>

    <nav class="main-nav" aria-label="Primary">
      ${navLinks}
    </nav>

    <div class="header-tools">
      <button class="lang-toggle" id="langToggle" aria-label="Switch language">
        <span class="lang-en">EN</span><span class="lang-sep">/</span><span class="lang-zh">中</span>
      </button>
      <button class="menu-btn" id="menuBtn" aria-label="Open menu">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>

  <div class="hot-strip">
    <div class="container hot-strip-inner">
      <span class="hot-strip-label" data-i18n="nav.hot">Hot brands</span>
      <a href="/brands/byd" class="hot-pill">BYD</a>
      <a href="/brands/xiaomi" class="hot-pill">Xiaomi</a>
      <a href="/brands/nio" class="hot-pill">NIO</a>
      <a href="/brands/xpeng" class="hot-pill">Xpeng</a>
      <a href="/brands/zeekr" class="hot-pill">Zeekr</a>
      <a href="/brands/geely" class="hot-pill">Geely</a>
    </div>
  </div>
</header>`;
}

const NEWSLETTER = `<section class="newsletter" aria-label="Newsletter subscription">
  <div class="container newsletter-inner">
    <div class="newsletter-text">
      <div class="newsletter-eyebrow" data-i18n="newsletter.eyebrow">The Daily</div>
      <h2 class="newsletter-title" data-i18n="newsletter.title">The best China car stories, curated weekday mornings.</h2>
      <p class="newsletter-deck" data-i18n="newsletter.deck">Every weekday morning. New model launches, overseas expansion, and the sales numbers that matter — in your inbox before the day starts. No spam. Unsubscribe anytime.</p>
    </div>
    <div class="newsletter-form-wrap">
      <form class="newsletter-form" id="newsletterForm">
        <input type="email" class="newsletter-input" id="newsletterEmail" required placeholder="your@email.com" data-i18n-attr="placeholder:newsletter.placeholder" aria-label="Email address" />
        <button type="submit" class="newsletter-btn" data-i18n="newsletter.cta">Subscribe</button>
      </form>
      <div class="newsletter-ok" id="newsletterOk" hidden data-i18n="newsletter.success">Thanks — first issue lands tomorrow at 7am.</div>
    </div>
  </div>
</section>`;

const FOOTER = `<footer class="site-footer">
  <div class="container footer-grid">
    <div class="footer-brand">
      <div class="footer-logo">TopChinaCar</div>
      <p data-i18n="footer.tagline">An editorial guide to the new era of Chinese automobiles, written for the world.</p>
    </div>
    <div class="footer-col">
      <h4 data-i18n="footer.explore">Explore</h4>
      <a href="/brands" data-i18n="nav.brands">Brands</a>
      <a href="/models" data-i18n="nav.models">Models</a>
      <a href="/news" data-i18n="nav.news">News</a>
      <a href="/tech" data-i18n="nav.tech">Tech</a>
    </div>
    <div class="footer-col">
      <h4 data-i18n="footer.about">About</h4>
      <a href="/about" data-i18n="nav.about">Our story</a>
      <a href="mailto:hello@topchinacar.com" data-i18n="footer.contact">Contact</a>
    </div>
    <div class="footer-col footer-meta">
      <h4 data-i18n="footer.follow">Follow</h4>
      <p>© 2026 TopChinaCar</p>
      <p data-i18n="footer.rights">Editorial, independent, worldwide.</p>
    </div>
  </div>
</footer>`;

const JSONLD = `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "${SITE}/#organization",
      "name": "TopChinaCar",
      "url": "${SITE}/",
      "logo": "${SITE}/images/hero-xiaomi.jpg",
      "description": "Independent editorial guide to Chinese automobiles for overseas readers.",
      "foundingDate": "2026",
      "sameAs": []
    },
    {
      "@type": "WebSite",
      "@id": "${SITE}/#website",
      "url": "${SITE}/",
      "name": "TopChinaCar",
      "publisher": { "@id": "${SITE}/#organization" },
      "inLanguage": ["en", "zh-CN"]
    },
    {
      "@type": "NewsMediaOrganization",
      "name": "TopChinaCar",
      "url": "${SITE}/",
      "diversityPolicy": "${SITE}/about",
      "ethicsPolicy": "${SITE}/about"
    }
  ]
}
</script>`;

function escAttr(s) {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

function pageHTML(route, meta, mainHTML) {
  const canonical = route === '/' ? SITE + '/' : SITE + route;
  meta = { ...meta, title: escAttr(meta.title), desc: escAttr(meta.desc) };
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${meta.title}</title>
<meta name="description" content="${meta.desc}" />
<meta name="author" content="TopChinaCar Editorial" />
<meta name="theme-color" content="#1a1a1a" />
<link rel="canonical" href="${canonical}" />

<!-- Open Graph -->
<meta property="og:type" content="${meta.ogType || 'website'}" />
<meta property="og:site_name" content="TopChinaCar" />
<meta property="og:title" content="${meta.title}" />
<meta property="og:description" content="${meta.desc}" />
<meta property="og:url" content="${canonical}" />
<meta property="og:image" content="${SITE}/images/hero-xiaomi.jpg" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:locale" content="en_US" />
<meta property="og:locale:alternate" content="zh_CN" />
${meta.published ? `<meta property="article:published_time" content="${meta.published}" />\n<meta property="article:section" content="China Auto Export" />` : ''}

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${meta.title}" />
<meta name="twitter:description" content="${meta.desc}" />
<meta name="twitter:image" content="${SITE}/images/hero-xiaomi.jpg" />

${route === '/' ? JSONLD + '\n' : ''}<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;0,700;0,900;1,500&family=Inter:wght@300;400;500;600;700&family=Noto+Serif+SC:wght@500;700;900&family=Noto+Sans+SC:wght@300;400;500;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/css/style.css" />
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' fill='%231a1a1a'/><text x='16' y='22' font-family='Playfair Display,serif' font-size='20' font-weight='900' text-anchor='middle' fill='%23d4302a'>T</text></svg>">
</head>
<body>

${headerHTML(route)}

<main id="app">${mainHTML}</main>

${NEWSLETTER}

${FOOTER}

<script src="/js/data.js?v=${BUILD_V}"></script>
<script src="/js/i18n.js?v=${BUILD_V}"></script>
<script src="/js/articles-data.js?v=${BUILD_V}"></script>
<script src="/js/pages.js?v=${BUILD_V}"></script>
<script src="/js/app.js?v=${BUILD_V}"></script>
</body>
</html>
`;
}

// ---- Generate pages ----
let count = 0;
for (const [route, meta] of Object.entries(PAGES)) {
  const mainHTML = PAGE_ROUTES[route]();
  fs.writeFileSync(path.join(ROOT, meta.file), pageHTML(route, meta, mainHTML));
  console.log(`✓ ${meta.file} (${mainHTML.length} chars of prerendered content)`);
  count++;
}

// ---- Brand detail pages (/brands/<id>) ----
const SITE_DATA = vm.runInContext('SITE_DATA', sandbox);
const BRANDS_OUT = path.join(ROOT, 'brands');
if (!fs.existsSync(BRANDS_OUT)) fs.mkdirSync(BRANDS_OUT);

const CATEGORY_LABEL = {
  group:    { en: 'Legacy Group', zh: '传统车企集团' },
  startup:  { en: 'New-Energy Startup', zh: '造车新势力' },
  subbrand: { en: 'Group Sub-Brand', zh: '集团子品牌' }
};

// Category-level buyer context (adds substance beyond the short brand blurb)
const CATEGORY_CONTEXT = {
  group: {
    en: 'As an established manufacturing group, it ships complete knock-down and fully-built vehicles worldwide, with mature homologation experience across left- and right-hand-drive markets. For dealers, that typically means broader spare-parts availability and factory-backed export documentation.',
    zh: '作为成熟的制造集团，其整车与 KD 件出口遍及全球，在左舵/右舵市场均有成熟的认证经验。对经销商而言，这通常意味着更完善的配件供应与厂家出口文件支持。'
  },
  startup: {
    en: 'As a new-energy startup, its lineup is EV-first with over-the-air software updates and rapid model cycles. Dealers importing these vehicles should verify charging-standard compatibility (CCS/GB-T) and local service arrangements for the destination market.',
    zh: '作为新势力车企，其产品以纯电为主，支持整车 OTA、车型迭代快。进口时需确认目的市场的充电标准兼容性（CCS/GB-T）与本地售后安排。'
  },
  subbrand: {
    en: 'It operates as an independent marque within its parent group, sharing platforms and the export network while targeting a distinct segment. Parts and homologation support generally flow through the parent group\'s international channels.',
    zh: '它作为母集团旗下的独立品牌运营，共享平台与出口网络，同时瞄准差异化细分市场。配件与认证支持通常通过母集团的国际渠道提供。'
  }
};

function langSpan(en, zh) {
  return `<span data-lang="en">${en}</span><span data-lang="zh" hidden>${zh}</span>`;
}

function brandMain(b) {
  const cat = CATEGORY_LABEL[b.category] || CATEGORY_LABEL.group;
  const ctx = CATEGORY_CONTEXT[b.category] || CATEGORY_CONTEXT.group;
  const models = SITE_DATA.models.filter(m => m.brand === b.name);
  const related = articles.filter(a =>
    (a.title_en + ' ' + (a.excerpt_en || '')).toLowerCase().includes(b.name.toLowerCase())).slice(0, 5);

  const fact = (labelEn, labelZh, val) => `
    <div class="brand-fact"><span class="spec-label">${langSpan(labelEn, labelZh)}</span><span class="spec-value">${val}</span></div>`;

  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">${langSpan(cat.en, cat.zh)}${b.parent_en ? ` · ${langSpan('Part of ' + b.parent_en, '隶属于' + (b.parent_zh || b.parent_en))}` : ''}</div>
      <h1 class="page-title">${b.name} <span style="font-size:.55em;color:#9ca3af;font-weight:500;">${b.cn}</span></h1>
      <p class="page-deck">${langSpan(b.desc_en, b.desc_zh)}</p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:920px;">
      <div class="brand-facts" style="display:flex;gap:36px;flex-wrap:wrap;margin-bottom:36px;">
        ${fact('Founded', '创立', b.founded)}
        ${fact('HQ', '总部', b.hq)}
        ${fact('Focus', '主攻', b.focus)}
        ${b.subBrands_en ? fact('Sub-brands', '旗下品牌', `${langSpan(b.subBrands_en, b.subBrands_zh || b.subBrands_en)}`) : ''}
      </div>
      <div style="font-size:16px;line-height:1.8;color:#374151;">
        <p>${langSpan(ctx.en, ctx.zh)}</p>
      </div>
      <div style="margin:32px 0;padding:24px;background:#f9fafb;border-left:3px solid #d4302a;">
        <h2 style="margin:0 0 8px;font-size:18px;">${langSpan(`Import ${b.name} vehicles`, `进口 ${b.name} 车辆`)}</h2>
        <p style="margin:0 0 16px;font-size:14px;line-height:1.7;color:#4b5563;">${langSpan(
          `Dealer or fleet buyer? Tell us your market and volume — we respond within 48 hours with availability and FOB/CIF quotes for ${b.name} models through licensed Chinese exporters.`,
          `经销商或车队买家？告诉我们目标市场与数量——48 小时内回复 ${b.name} 车型的货源与 FOB/CIF 报价，由持牌中国出口商执行。`)}</p>
        <a href="/quote?model=${encodeURIComponent(b.name)}" class="btn btn-primary">${langSpan('Request a quote', '提交询价')}</a>
      </div>
      ${models.length ? `
      <h2 style="font-size:22px;margin:40px 0 20px;">${langSpan('Featured ' + b.name + ' models', b.name + ' 明星车型')}</h2>
      <div class="models-grid">
        ${models.map(m => modelCardHTML(m, 'en')).join('')}
      </div>` : ''}
      ${related.length ? `
      <h2 style="font-size:22px;margin:40px 0 20px;">${langSpan('Latest ' + b.name + ' news', b.name + ' 最新动态')}</h2>
      <ul style="list-style:none;padding:0;margin:0;">
        ${related.map(a => `<li style="margin-bottom:14px;"><a href="/news/${a.slug}" style="color:inherit;text-decoration:none;"><strong>${a.title_en}</strong></a><br/><span style="font-size:13px;color:#9ca3af;">${a.date}</span></li>`).join('')}
      </ul>` : ''}
      <p style="margin-top:40px;"><a href="/brands" style="color:var(--accent, #d4302a);font-family:var(--mono);font-size:13px;">← All 31 Chinese car brands</a></p>
    </div>
  </section>`;
}

function brandJsonLd(b) {
  return `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Brand",
      "name": "${b.name}",
      "alternateName": "${b.cn}",
      "url": "${SITE}/brands/${b.id}",
      "description": ${JSON.stringify(b.desc_en)}
    },
    {
      "@type": "BreadcrumbList",
      "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Home", "item": "${SITE}/"},
        {"@type": "ListItem", "position": 2, "name": "Brands", "item": "${SITE}/brands"},
        {"@type": "ListItem", "position": 3, "name": "${b.name}", "item": "${SITE}/brands/${b.id}"}
      ]
    }
  ]
}
</script>`;
}

// ---- Brand auto-linker: first mention of each brand in article text → /brands/<id> ----
// Works on HTML strings; skips text inside <a>…</a> and headings.
function linkifyBrands(html, lang) {
  if (!html) return html;
  const done = new Set();
  const segments = html.split(/(<[^>]+>)/);
  let skipDepth = 0;
  const brands = [...SITE_DATA.brands].sort((x, y) => y.name.length - x.name.length);
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    if (seg.startsWith('<')) {
      if (/^<(a|h[1-6])[\s>]/i.test(seg)) skipDepth++;
      else if (/^<\/(a|h[1-6])>/i.test(seg)) skipDepth = Math.max(0, skipDepth - 1);
      continue;
    }
    if (skipDepth > 0 || !seg.trim()) continue;
    let text = seg;
    for (const b of brands) {
      if (done.has(b.id)) continue;
      const needle = lang === 'zh' ? b.cn : b.name;
      if (!needle) continue;
      let idx = -1;
      if (lang === 'zh') {
        idx = text.indexOf(needle);
      } else {
        const re = new RegExp('\\b' + needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b');
        const m2 = text.match(re);
        idx = m2 ? m2.index : -1;
      }
      if (idx === -1) continue;
      text = text.slice(0, idx)
        + `<a href="/brands/${b.id}" style="color:inherit;text-decoration:underline;text-decoration-color:#d4302a;text-underline-offset:3px;">${needle}</a>`
        + text.slice(idx + needle.length);
      done.add(b.id);
    }
    segments[i] = text;
  }
  return segments.join('');
}

const modelCardHTML = vm.runInContext('modelCardHTML', sandbox);
for (const b of SITE_DATA.brands) {
  const catEn = (CATEGORY_LABEL[b.category] || CATEGORY_LABEL.group).en;
  const html = pageHTML(`/brands/${b.id}`, {
    title: `${b.name} (${b.cn}) Export — Models, Markets & Wholesale Quotes | TopChinaCar`,
    desc: `${b.desc_en} ${catEn}, founded ${b.founded}, HQ ${b.hq}. Dealer and fleet export quotes for ${b.name} vehicles through licensed Chinese exporters.`.slice(0, 300)
  }, brandMain(b)).replace('</head>', brandJsonLd(b) + '\n</head>');
  fs.writeFileSync(path.join(BRANDS_OUT, `${b.id}.html`), html);
}
console.log(`✓ ${SITE_DATA.brands.length} brand pages → brands/`);

// ---- Model detail pages (/models/<id>) ----
const MODELS_OUT = path.join(ROOT, 'models');
if (!fs.existsSync(MODELS_OUT)) fs.mkdirSync(MODELS_OUT);

function modelMain(m, brand) {
  const cat = brand ? (CATEGORY_LABEL[brand.category] || CATEGORY_LABEL.group) : CATEGORY_LABEL.group;
  const ctx = brand ? (CATEGORY_CONTEXT[brand.category] || CATEGORY_CONTEXT.group) : CATEGORY_CONTEXT.group;
  const related = articles.filter(a =>
    (a.title_en + ' ' + (a.excerpt_en || '')).toLowerCase().includes(m.brand.toLowerCase())
    || (a.title_en + ' ' + (a.excerpt_en || '')).toLowerCase().includes(m.name.toLowerCase())).slice(0, 5);
  const siblings = SITE_DATA.models.filter(x => x.brand === m.brand && x.id !== m.id);
  const fact = (labelEn, labelZh, val) => `
    <div class="brand-fact"><span class="spec-label">${langSpan(labelEn, labelZh)}</span><span class="spec-value">${val}</span></div>`;
  const visual = m.image
    ? `<div style="margin:0 0 32px;border-radius:12px;overflow:hidden;position:relative;"><img src="/${m.image}" alt="${m.brand} ${m.name}" style="width:100%;display:block;" />${m.imageCredit ? `<span class="img-credit">Photo: ${m.imageCredit}</span>` : ''}</div>`
    : '';
  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">${brand ? `<a href="/brands/${brand.id}" style="color:inherit;text-decoration:none;">${m.brand}</a>` : m.brand} · ${langSpan(cat.en, cat.zh)}</div>
      <h1 class="page-title">${m.brand} ${m.name}</h1>
      <p class="page-deck">${langSpan(m.tag_en, m.tag_zh)}</p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:920px;">
      ${visual}
      <div class="brand-facts" style="display:flex;gap:36px;flex-wrap:wrap;margin-bottom:36px;">
        ${fact('Range', '续航', m.range)}
        ${fact('0–100 km/h', '零百加速', m.accel)}
        ${fact('From', '起价', m.price)}
      </div>
      <div style="font-size:16px;line-height:1.8;color:#374151;">
        <p>${langSpan(ctx.en, ctx.zh)}</p>
        <p style="font-size:13px;color:#9ca3af;">${langSpan(
          'Prices shown are indicative list prices in the named market and change frequently — confirm current export pricing via a quote request.',
          '页面价格为对应市场的指导价，波动频繁——实际出口价格以询价回复为准。')}</p>
      </div>
      <div style="margin:32px 0;padding:24px;background:#f9fafb;border-left:3px solid #d4302a;">
        <h2 style="margin:0 0 8px;font-size:18px;">${langSpan(`Import the ${m.brand} ${m.name}`, `进口 ${m.brand} ${m.name}`)}</h2>
        <p style="margin:0 0 16px;font-size:14px;line-height:1.7;color:#4b5563;">${langSpan(
          `Dealer or fleet buyer? Tell us your market and volume — we respond within 48 hours with availability and FOB/CIF quotes for the ${m.name} through licensed Chinese exporters.`,
          `经销商或车队买家？告诉我们目标市场与数量——48 小时内回复 ${m.name} 的货源与 FOB/CIF 报价，由持牌中国出口商执行。`)}</p>
        <a href="/quote?model=${encodeURIComponent(m.brand + ' ' + m.name)}" class="btn btn-primary">${langSpan('Request a quote', '提交询价')}</a>
      </div>
      ${siblings.length ? `
      <h2 style="font-size:22px;margin:40px 0 20px;">${langSpan('More ' + m.brand + ' models', m.brand + ' 其他车型')}</h2>
      <ul style="list-style:none;padding:0;margin:0;">
        ${siblings.map(s => `<li style="margin-bottom:10px;"><a href="/models/${s.id}" style="color:inherit;text-decoration:none;"><strong>${s.brand} ${s.name}</strong></a> <span style="font-size:13px;color:#9ca3af;">· ${s.range} · ${s.price}</span></li>`).join('')}
      </ul>` : ''}
      ${related.length ? `
      <h2 style="font-size:22px;margin:40px 0 20px;">${langSpan('Related news', '相关动态')}</h2>
      <ul style="list-style:none;padding:0;margin:0;">
        ${related.map(a => `<li style="margin-bottom:14px;"><a href="/news/${a.slug}" style="color:inherit;text-decoration:none;"><strong>${a.title_en}</strong></a><br/><span style="font-size:13px;color:#9ca3af;">${a.date}</span></li>`).join('')}
      </ul>` : ''}
      <p style="margin-top:40px;">
        ${brand ? `<a href="/brands/${brand.id}" style="color:var(--accent, #d4302a);font-family:var(--mono);font-size:13px;">← ${m.brand} brand profile</a> · ` : ''}
        <a href="/models" style="color:var(--accent, #d4302a);font-family:var(--mono);font-size:13px;">← All featured models</a>
      </p>
    </div>
  </section>`;
}

function modelJsonLd(m) {
  return `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Product",
      "name": "${m.brand} ${m.name}",
      "brand": {"@type": "Brand", "name": "${m.brand}"},
      "url": "${SITE}/models/${m.id}",
      "description": ${JSON.stringify(m.tag_en)},
      "category": "Vehicle"
    },
    {
      "@type": "BreadcrumbList",
      "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Home", "item": "${SITE}/"},
        {"@type": "ListItem", "position": 2, "name": "Models", "item": "${SITE}/models"},
        {"@type": "ListItem", "position": 3, "name": "${m.brand} ${m.name}", "item": "${SITE}/models/${m.id}"}
      ]
    }
  ]
}
</script>`;
}

let modelCount = 0;
for (const m of SITE_DATA.models) {
  if (!m.id) continue;
  const brand = SITE_DATA.brands.find(b => b.name === m.brand);
  const html = pageHTML(`/models/${m.id}`, {
    title: `${m.brand} ${m.name} Export — Specs, Price & Wholesale Quotes | TopChinaCar`,
    desc: `${m.tag_en} Range ${m.range}, 0-100 km/h ${m.accel}, from ${m.price}. Dealer and fleet export quotes for the ${m.brand} ${m.name} through licensed Chinese exporters.`.slice(0, 300)
  }, modelMain(m, brand)).replace('</head>', modelJsonLd(m) + '\n</head>');
  fs.writeFileSync(path.join(MODELS_OUT, `${m.id}.html`), html);
  modelCount++;
}
console.log(`✓ ${modelCount} model pages → models/`);

// ---- Feature story pages (/stories/<slug>) ----
const STORIES_OUT = path.join(ROOT, 'stories');
if (!fs.existsSync(STORIES_OUT)) fs.mkdirSync(STORIES_OUT);

function storyMain(f, s) {
  const langBlock = (lang, html) => `<div data-lang="${lang}"${lang === 'zh' ? ' hidden' : ''}>${linkifyBrands(html, lang)}</div>`;
  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">${langSpan(f.tag_en, f.tag_zh)} · ${langSpan(f.meta_en, f.meta_zh)}</div>
      <h1 class="page-title">${langSpan(f.title_en, f.title_zh)}</h1>
      <p class="page-deck">${langSpan(f.desc_en, f.desc_zh)}</p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:820px;">
      ${f.image ? `<div style="margin:0 0 36px;border-radius:12px;overflow:hidden;position:relative;"><img src="/${f.image}" alt="${f.title_en}" style="width:100%;display:block;" />${f.imageCredit ? `<span class="img-credit">Photo: ${f.imageCredit}</span>` : ''}</div>` : ''}
      <article class="article-body" style="font-size:16px;line-height:1.8;">
        ${langBlock('en', s.html_en)}
        ${langBlock('zh', s.html_zh || s.html_en)}
      </article>
      <div style="margin:44px 0 0;padding:26px 28px;background:#f9fafb;border-left:3px solid #d4302a;">
        <h2 style="margin:0 0 8px;font-size:19px;">${langSpan('Import these vehicles', '进口这些车辆')}</h2>
        <p style="margin:0 0 16px;font-size:14px;line-height:1.7;color:#4b5563;">${langSpan(
          'Dealer, fleet or importer? We source availability and FOB/CIF quotes for any Chinese brand through licensed exporters — response within 48 hours.',
          '经销商、车队或进口商？我们通过持牌出口商为任意中国品牌匹配货源与 FOB/CIF 报价——48 小时内回复。')}</p>
        <a href="/quote" class="btn btn-primary">${langSpan('Request a quote', '提交询价')}</a>
      </div>
      <p style="margin-top:32px;"><a href="/news" style="color:var(--accent);font-family:var(--mono);font-size:13px;">← All news & features</a></p>
    </div>
  </section>`;
}

function storyJsonLd(f, s) {
  return `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": ${JSON.stringify(f.title_en)},
  "description": ${JSON.stringify(f.desc_en)},
  "datePublished": "${s.date}",
  "inLanguage": ["en", "zh-CN"],
  "mainEntityOfPage": "${SITE}/stories/${f.slug}",
  "author": {"@type": "Organization", "name": "TopChinaCar", "url": "${SITE}/"},
  "publisher": {"@id": "${SITE}/#organization"}
}
</script>`;
}

let storyCount = 0;
for (const s of SITE_STORIES) {
  const f = (SITE_DATA.features || []).find(x => x.slug === s.slug);
  if (!f) { console.error(`✗ story ${s.slug} has no matching features[] entry — skipped`); continue; }
  const html = pageHTML(`/stories/${f.slug}`, {
    title: `${f.title_en} | TopChinaCar`,
    desc: f.desc_en.slice(0, 300),
    ogType: 'article',
    published: s.date
  }, storyMain(f, s)).replace('</head>', storyJsonLd(f, s) + '\n</head>');
  fs.writeFileSync(path.join(STORIES_OUT, `${f.slug}.html`), html);
  storyCount++;
}
if (storyCount) console.log(`✓ ${storyCount} feature stories → stories/`);

// ---- Daily article pages (/news/<slug>) ----
const NEWS_OUT = path.join(ROOT, 'news');
if (!fs.existsSync(NEWS_OUT)) fs.mkdirSync(NEWS_OUT);
function articleMain(a) {
  const dateNice = new Date(a.date + 'T00:00:00Z').toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' });
  const langBlock = (lang, html) => `<div data-lang="${lang}"${lang === 'zh' ? ' hidden' : ''}>${linkifyBrands(html, lang)}</div>`;
  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow"><span data-lang="en">${a.tag_en || 'Daily Briefing'} · ${dateNice}</span><span data-lang="zh" hidden>${a.tag_zh || '每日简报'} · ${a.date}</span></div>
      <h1 class="page-title"><span data-lang="en">${a.title_en}</span><span data-lang="zh" hidden>${a.title_zh || a.title_en}</span></h1>
      <p class="page-deck"><span data-lang="en">${a.excerpt_en || ''}</span><span data-lang="zh" hidden>${a.excerpt_zh || ''}</span></p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:820px;">
      <article class="article-body" style="font-size:16px;line-height:1.8;">
        ${langBlock('en', a.html_en)}
        ${langBlock('zh', a.html_zh || a.html_en)}
      </article>
      <div style="margin:44px 0 0;padding:26px 28px;background:#f9fafb;border-left:3px solid #d4302a;">
        <h2 style="margin:0 0 8px;font-size:19px;">${langSpan('Import these vehicles', '进口这些车辆')}</h2>
        <p style="margin:0 0 16px;font-size:14px;line-height:1.7;color:#4b5563;">${langSpan(
          'Dealer, fleet or importer? We source availability and FOB/CIF quotes for any Chinese brand through licensed exporters — response within 48 hours.',
          '经销商、车队或进口商？我们通过持牌出口商为任意中国品牌匹配货源与 FOB/CIF 报价——48 小时内回复。')}</p>
        <a href="/quote" class="btn btn-primary">${langSpan('Request a quote', '提交询价')}</a>
      </div>
      <p style="margin-top:32px;"><a href="/news" style="color:var(--accent);font-family:var(--mono);font-size:13px;">← All news</a></p>
    </div>
  </section>`;
}

function articleJsonLd(a) {
  return `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "NewsArticle",
  "headline": ${JSON.stringify(a.title_en)},
  "description": ${JSON.stringify(a.excerpt_en || a.title_en)},
  "datePublished": "${a.date}",
  "inLanguage": ["en", "zh-CN"],
  "mainEntityOfPage": "${SITE}/news/${a.slug}",
  "author": {"@type": "Organization", "name": "TopChinaCar", "url": "${SITE}/"},
  "publisher": {"@id": "${SITE}/#organization"}
}
</script>`;
}

for (const a of articles) {
  const route = `/news/${a.slug}`;
  const html = pageHTML(route, {
    title: `${a.title_en} | TopChinaCar`,
    desc: (a.excerpt_en || a.title_en).slice(0, 300),
    ogType: 'article',
    published: a.date
  }, articleMain(a)).replace('</head>', articleJsonLd(a) + '\n</head>');
  fs.writeFileSync(path.join(NEWS_OUT, `${a.slug}.html`), html);
}
if (articles.length) console.log(`✓ ${articles.length} article page(s) → news/`);

// ---- 404 ----
const notFoundMain = `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">404</div>
      <h1 class="page-title">Page not found</h1>
      <p class="page-deck">The page you are looking for does not exist. <a href="/" style="color:var(--accent);">Back to the homepage</a> · <a href="/brands" style="color:var(--accent);">Brand Index</a> · <a href="/news" style="color:var(--accent);">News</a></p>
    </div>
  </section>`;
fs.writeFileSync(path.join(ROOT, '404.html'),
  pageHTML('/', { title: 'Page Not Found | TopChinaCar', desc: 'The page you are looking for does not exist.' }, notFoundMain));
console.log('✓ 404.html');

// ---- sitemap.xml ----
const today = new Date().toISOString().slice(0, 10);
const staticUrls = Object.keys(PAGES).map(r =>
  `  <url><loc>${r === '/' ? SITE + '/' : SITE + r}</loc><lastmod>${today}</lastmod></url>`);
const brandUrls = SITE_DATA.brands.map(b =>
  `  <url><loc>${SITE}/brands/${b.id}</loc><lastmod>${today}</lastmod></url>`);
const modelUrls = SITE_DATA.models.filter(m => m.id).map(m =>
  `  <url><loc>${SITE}/models/${m.id}</loc><lastmod>${today}</lastmod></url>`);
const storyUrls = SITE_STORIES
  .filter(s => (SITE_DATA.features || []).some(f => f.slug === s.slug))
  .map(s => `  <url><loc>${SITE}/stories/${s.slug}</loc><lastmod>${s.date}</lastmod></url>`);
const articleUrls = articles.map(a =>
  `  <url><loc>${SITE}/news/${a.slug}</loc><lastmod>${a.date}</lastmod></url>`);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${staticUrls.concat(brandUrls, modelUrls, storyUrls, articleUrls).join('\n')}
</urlset>
`;
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);
console.log('✓ sitemap.xml');

console.log(`\nDone — ${count} pages + 404 + sitemap.`);
