#!/usr/bin/env node
// ============ STATIC PRERENDER ============
// Generates one fully-rendered HTML file per route so search engines see real
// content at real URLs. Run after editing js/data.js or js/i18n.js:
//   node build.js
// Output: index.html, brands.html, models.html, news.html, tech.html,
//         about.html, 404.html  (Vercel cleanUrls serves /chinese-car-brands from brands.html)

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = __dirname;
const SITE = 'https://www.topchinacar.com';
const BUILD_V = new Date().toISOString().slice(0, 16).replace(/[-:T]/g, ''); // cache-busting version
const TODAY = new Date().toISOString().slice(0, 10);
const DEFAULT_OG_IMAGE = 'images/hero-xiaomi.jpg';
const SITE_LOGO = 'images/topchinacar-logo.svg';

// ---- Collect daily articles (articles/*.json, written by the GCP pipeline) ----
const ARTICLES_DIR = path.join(ROOT, 'articles');
let articles = [];
if (fs.existsSync(ARTICLES_DIR)) {
  articles = fs.readdirSync(ARTICLES_DIR)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      try { return JSON.parse(fs.readFileSync(path.join(ARTICLES_DIR, f), 'utf-8')); }
      catch (e) { console.error(`✗ skipping bad article ${f}: ${e.message}`); return null; }
    })
    .filter(a => a && a.slug && a.date && a.title_en && a.html_en)
    .sort((a, b) => b.date.localeCompare(a.date) || b.slug.localeCompare(a.slug));
}

// Lightweight index (no article bodies) shared with the client for the News page
const articlesIndex = articles.map(a => ({
  slug: a.slug, date: a.date,
  title_en: a.title_en, title_zh: a.title_zh || a.title_en,
  excerpt_en: a.excerpt_en || '', excerpt_zh: a.excerpt_zh || a.excerpt_en || '',
  tag_en: a.tag_en || 'Daily Briefing', tag_zh: a.tag_zh || '每日简报'
}));
fs.writeFileSync(path.join(ROOT, 'js', 'articles-data.js'),
  '// Generated by build.js — do not edit\nconst SITE_ARTICLES = '
  + JSON.stringify(articlesIndex, null, 2) + ';\n');

// ---- Load site scripts in a sandbox with a minimal document stub ----
const sandbox = {
  document: { documentElement: { lang: 'en' } },
  module: undefined,
  console
};
vm.createContext(sandbox);
for (const f of ['js/data.js', 'js/i18n.js', 'js/articles-data.js', 'js/pages.js']) {
  vm.runInContext(fs.readFileSync(path.join(ROOT, f), 'utf-8'), sandbox, { filename: f });
}
const PAGE_ROUTES = vm.runInContext('PAGE_ROUTES', sandbox);

// ============ Chinese mirror (/zh/...) helpers ============
const I18N_ZH = vm.runInContext('I18N.zh', sandbox);
const I18N_EN = vm.runInContext('I18N.en', sandbox);
const setSandboxLang = l => vm.runInContext(`document.documentElement.lang='${l}'`, sandbox);

// Post-process a rendered page into its Chinese variant:
//  - translate header/footer/newsletter chrome (data-i18n / data-i18n-attr)
//  - flip bilingual data-lang blocks (zh visible, en hidden)
//  - prefix internal links with /zh (assets, api and external links untouched)
function zhChrome(html) {
  // Translate only nodes still holding the exact English dictionary value —
  // re-rendered zh content (already Chinese) is left untouched.
  html = html.replace(/(<[^>]*data-i18n="([^"]+)"[^>]*>)([^<]*)/g,
    (all, open, key, txt) =>
      (I18N_ZH[key] !== undefined && txt.trim() === String(I18N_EN[key] || '').trim())
        ? open + I18N_ZH[key] : all);
  html = html.replace(/placeholder="[^"]*"([^>]*data-i18n-attr="placeholder:([^"]+)")/g,
    (all, rest, key) => I18N_ZH[key] !== undefined ? `placeholder="${I18N_ZH[key]}"${rest}` : all);
  html = html
    .replace(/data-lang="zh" hidden/g, 'data-lang="zh" data-zh-keep')
    .replace(/data-lang="en"/g, 'data-lang="en" hidden')
    .replace(/data-lang="zh" data-zh-keep/g, 'data-lang="zh"');
  html = html.replace(/href="\/(?!zh\/|zh"|images\/|css\/|js\/|api\/|cdn-cgi\/)/g, 'href="/zh/');
  return html;
}

function writeZh(relPath, html) {
  const dest = path.join(ROOT, 'zh', relPath);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, html);
}

const PAGES_ZH = {
  '/': { title: 'TopChinaCar | 中国汽车全球化新闻：新能源、出口与全球市场', desc: 'TopChinaCar 面向国际读者报道中国汽车品牌、电动车、出口市场、政策变化与全球扩张。' },
  '/editorial-policy': { title: 'TopChinaCar 编辑方针与信源标准', desc: 'TopChinaCar 如何报道中国汽车全球化：内容主线、信源标准、文章结构、独立性与更正政策。' },
  '/contact': { title: '联系 TopChinaCar — 媒体、市场情报与合作', desc: '媒体、市场情报、经销商与合作事宜，请联系 TopChinaCar。48 小时内回复。' },
  '/newsletter': { title: '每日出海简报 — 邮件订阅 | TopChinaCar', desc: '面向全球市场的中国汽车新闻，每个工作日早晨送达：出口、市场进入、工厂、关税与新车——附信源链接。' },
  '/chinese-car-brands': { title: '中国汽车品牌大全 | TopChinaCar', desc: '中国汽车品牌指南：比亚迪、吉利、上汽、奇瑞、长城、蔚来、小鹏、理想、小米、零跑及其子品牌。' },
  '/models': { title: '中国电动车明星车型 — 续航、价格与参数 | TopChinaCar', desc: '定义新时代的中国电动车：比亚迪海豹、小米 SU7 Ultra、蔚来 ET9、小鹏 G6、理想 MEGA、极氪 001——真实续航、零百加速与美元指导价。' },
  '/news': { title: '中国汽车出海与电动车行业新闻 | TopChinaCar', desc: '中国汽车出口、新车发布、电池技术与政策动态的精选报道，以及每个工作日更新的出海简报。' },
  '/tech': { title: '中国电动车技术解读：800V、城市智驾、刀片电池 | TopChinaCar', desc: '深度解读中国汽车领先背后的技术：800V 高压平台、城市级智能驾驶、智能座舱、刀片电池与 CTB 电池车身一体化。' },
  '/about': { title: '关于 TopChinaCar — 独立的中国汽车编辑报道', desc: 'TopChinaCar 是面向海外读者的独立双语编辑出版物，讲解中国汽车——品牌、车型、技术与人。不吹捧，不贬低。' },
  '/quote': { title: '商业联系与合作咨询 | TopChinaCar', desc: '面向合作、市场情报和商业咨询的联系页面。TopChinaCar 的核心定位仍是独立新闻与信息报道。', robots: 'noindex,follow' },
  '/privacy': { title: 'TopChinaCar 隐私政策与数据使用说明', desc: 'TopChinaCar 如何收集、使用与保护您的信息：询价表单、邮件订阅与网站分析的数据用途说明。' }
};


// Feature story bodies (build-time only — never shipped to the client)
let SITE_STORIES = [];
if (fs.existsSync(path.join(ROOT, 'js', 'stories-data.js'))) {
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'js', 'stories-data.js'), 'utf-8'), sandbox, { filename: 'js/stories-data.js' });
  SITE_STORIES = vm.runInContext('typeof SITE_STORIES !== "undefined" ? SITE_STORIES : []', sandbox);
}
const SITE_DATA = vm.runInContext('SITE_DATA', sandbox);

// ---- Per-page metadata ----
const PAGES = {
  '/': {
    file: 'index.html',
    title: 'TopChinaCar | Chinese Auto News, EVs, Exports and Global Markets',
    desc: 'TopChinaCar covers Chinese car brands, electric vehicles, export markets, policy changes, and global expansion for international readers.'
  },
  '/chinese-car-brands': {
    file: 'chinese-car-brands.html',
    title: 'Chinese Car Brands: BYD, Geely, NIO & More | TopChinaCar',
    desc: 'A field guide to 30 Chinese automakers, EV startups and sub-brands, with founding dates, headquarters, focus areas and export footprint.'
  },
  '/models': {
    file: 'models.html',
    title: 'Featured Chinese EV Models — Range, Price & Specs | TopChinaCar',
    desc: 'The Chinese EVs defining the new era: BYD Seal, Xiaomi SU7 Ultra, NIO ET9, Xpeng G6, Li Auto MEGA, Zeekr 001 — with real range figures, 0-100 times and prices in ¥/$/€.'
  },
  '/news': {
    file: 'news.html',
    title: 'China Auto Export & EV Industry News | TopChinaCar',
    desc: 'Curated reporting on Chinese car exports, new model launches, battery technology and policy — plus the weekly China Export Watch column.'
  },
  '/tech': {
    file: 'tech.html',
    title: 'Chinese EV Technology Explained: 800V, City Autonomy, Blade Batteries | TopChinaCar',
    desc: 'Deep dives into the technologies behind China\'s automotive lead: 800V high-voltage platforms, city-level autonomous driving, smart cockpits, and Blade & CTB batteries.'
  },
  '/about': {
    file: 'about.html',
    title: 'About TopChinaCar — Independent Editorial on Chinese Automakers',
    desc: 'TopChinaCar is an independent, bilingual editorial publication explaining Chinese automobiles to overseas readers — brands, cars, technology and people. No hype, no dismissal.'
  },
  '/quote': {
    file: 'quote.html',
    title: 'Commercial Inquiries | TopChinaCar',
    desc: 'Contact page for partnerships, market intelligence and commercial inquiries. TopChinaCar remains an independent news and information site.',
    robots: 'noindex,follow'
  },
  '/privacy': {
    file: 'privacy.html',
    title: 'Privacy Policy | TopChinaCar',
    desc: 'How TopChinaCar collects, uses and protects your information: quote inquiries, newsletter subscriptions and site analytics.'
  },
  '/editorial-policy': {
    file: 'editorial-policy.html',
    title: 'Editorial Policy | TopChinaCar',
    desc: 'How TopChinaCar reports on China auto globalization: coverage pillars, sourcing standards, article structure, independence and corrections.'
  },
  '/contact': {
    file: 'contact.html',
    title: 'Contact TopChinaCar — Media, Market Intelligence & Partnerships',
    desc: 'For media, market intelligence, dealer and partnership inquiries, contact TopChinaCar. We respond within 48 hours.'
  },
  '/newsletter': {
    file: 'newsletter.html',
    title: 'The Daily Briefing — China Auto News by Email | TopChinaCar',
    desc: 'China auto news for global markets, in your inbox every weekday morning: exports, market entries, plants, tariffs and launches — with sources linked.'
  }
};

const NAV = [
  ['/news', 'nav.news', 'News'],
  ['/china-ev-news', 'nav.ev', 'EV'],
  ['/china-car-export-news', 'nav.exports', 'Exports'],
  ['/chinese-car-brands', 'nav.brands', 'Brands'],
  ['/markets', 'nav.markets', 'Markets'],
  ['/policy', 'nav.policy', 'Policy'],
  ['/data', 'nav.data', 'Data'],
  ['/analysis', 'nav.analysis', 'Analysis']
];

function headerHTML(route) {
  const navLinks = NAV.map(([href, key, label]) =>
    `<a href="${href}"${href === route ? ' class="active"' : ''} data-i18n="${key}">${label}</a>`).join('\n      ');
  return `<header class="site-header" id="siteHeader">
  <div class="container header-inner">
    <a href="/" class="logo" aria-label="TopChinaCar home">
      <svg width="28" height="28" viewBox="0 0 32 32" fill="none" aria-hidden="true">
        <rect width="32" height="32" rx="2" fill="currentColor"/>
        <text x="16" y="23" font-family="Playfair Display,serif" font-size="22" font-weight="900" text-anchor="middle" fill="#d4302a">T</text>
      </svg>
      <span class="logo-text">
        <span class="logo-main">TopChinaCar</span>
        <span class="logo-sub" data-i18n="logo.sub">China Auto News for Global Markets</span>
      </span>
    </a>

    <nav class="main-nav" id="primaryNav" aria-label="Primary">
      ${navLinks}
    </nav>

    <div class="header-tools">
      <button class="lang-toggle" id="langToggle" aria-label="Switch language">
        <span class="lang-en">EN</span><span class="lang-sep">/</span><span class="lang-zh">中</span>
      </button>
      <button class="menu-btn" id="menuBtn" aria-label="Open menu" aria-controls="primaryNav" aria-expanded="false">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>

  <div class="hot-strip">
    <div class="container hot-strip-inner">
      <span class="hot-strip-label" data-i18n="nav.hot">Hot brands</span>
      <a href="/chinese-car-brands/byd" class="hot-pill">BYD</a>
      <a href="/chinese-car-brands/xiaomi" class="hot-pill">Xiaomi</a>
      <a href="/chinese-car-brands/nio" class="hot-pill">NIO</a>
      <a href="/chinese-car-brands/xpeng" class="hot-pill">Xpeng</a>
      <a href="/chinese-car-brands/zeekr" class="hot-pill">Zeekr</a>
      <a href="/chinese-car-brands/geely" class="hot-pill">Geely</a>
    </div>
  </div>
</header>`;
}

const NEWSLETTER = `<section class="newsletter" aria-label="Newsletter subscription">
  <div class="container newsletter-inner">
    <div class="newsletter-text">
      <div class="newsletter-eyebrow" data-i18n="newsletter.eyebrow">The Daily</div>
      <h2 class="newsletter-title" data-i18n="newsletter.title">The best China car stories, curated weekday mornings.</h2>
      <p class="newsletter-deck" data-i18n="newsletter.deck">Every weekday morning. New model launches, overseas expansion, and the sales numbers that matter — in your inbox before the day starts. No spam. Unsubscribe anytime.</p>
    </div>
    <div class="newsletter-form-wrap">
      <form class="newsletter-form" id="newsletterForm">
        <input type="email" class="newsletter-input" id="newsletterEmail" required placeholder="your@email.com" data-i18n-attr="placeholder:newsletter.placeholder" aria-label="Email address" />
        <button type="submit" class="newsletter-btn" data-i18n="newsletter.cta">Subscribe</button>
      </form>
      <div class="newsletter-ok" id="newsletterOk" hidden data-i18n="newsletter.success">Thanks — first issue lands tomorrow at 7am.</div>
      <p style="margin:10px 0 0;font-size:12px;color:#9ca3af;"><span data-i18n="newsletter.privacy1">By subscribing you agree to the</span> <a href="/privacy" data-i18n="footer.privacy" style="color:inherit;text-decoration:underline;">Privacy Policy</a><span data-i18n="newsletter.privacy2">.</span></p>
    </div>
  </div>
</section>`;

const FOOTER = `<footer class="site-footer">
  <div class="container footer-grid">
    <div class="footer-brand">
      <div class="footer-logo">TopChinaCar</div>
      <p data-i18n="footer.tagline">An editorial guide to the new era of Chinese automobiles, written for the world.</p>
    </div>
    <div class="footer-col">
      <h4 data-i18n="footer.explore">Explore</h4>
      <a href="/news" data-i18n="nav.news">News</a>
      <a href="/china-ev-news" data-i18n="nav.ev">EV</a>
      <a href="/china-car-export-news" data-i18n="nav.exports">Exports</a>
      <a href="/chinese-car-brands" data-i18n="nav.brands">Brands</a>
      <a href="/markets" data-i18n="nav.markets">Markets</a>
      <a href="/models" data-i18n="nav.models">Models</a>
    </div>
    <div class="footer-col">
      <h4 data-i18n="footer.about">About</h4>
      <a href="/about" data-i18n="nav.about">Our story</a>
      <a href="/editorial-policy" data-i18n="footer.editorial">Editorial Policy</a>
      <a href="/newsletter" data-i18n="footer.newsletter">Newsletter</a>
      <a href="/contact" data-i18n="footer.contact">Contact</a>
      <a href="/privacy" data-i18n="footer.privacy">Privacy Policy</a>
    </div>
    <div class="footer-col footer-meta">
      <h4 data-i18n="footer.follow">Follow</h4>
      <p>© 2026 TopChinaCar</p>
      <p data-i18n="footer.rights">Editorial, independent, worldwide.</p>
    </div>
  </div>
</footer>`;

const JSONLD = `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "${SITE}/#organization",
      "name": "TopChinaCar",
      "url": "${SITE}/",
      "logo": {
        "@type": "ImageObject",
        "url": "${SITE}/${SITE_LOGO}",
        "width": 512,
        "height": 512
      },
      "description": "Independent news site covering Chinese automakers, EVs, exports and global market expansion.",
      "foundingDate": "2026",
      "sameAs": []
    },
    {
      "@type": "WebSite",
      "@id": "${SITE}/#website",
      "url": "${SITE}/",
      "name": "TopChinaCar",
      "publisher": { "@id": "${SITE}/#organization" },
      "inLanguage": ["en", "zh-CN"]
    },
    {
      "@type": "NewsMediaOrganization",
      "@id": "${SITE}/#newsmedia",
      "name": "TopChinaCar",
      "url": "${SITE}/",
      "logo": {
        "@type": "ImageObject",
        "url": "${SITE}/${SITE_LOGO}",
        "width": 512,
        "height": 512
      },
      "diversityPolicy": "${SITE}/about",
      "ethicsPolicy": "${SITE}/about"
    }
  ]
}
</script>`;

function escAttr(s) {
  return String(s || '').replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

function truncateMeta(s, max = 160) {
  s = String(s || '').replace(/\s+/g, ' ').trim();
  if (s.length <= max) return s;
  const cut = s.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(' ');
  return (lastSpace > 80 ? cut.slice(0, lastSpace) : cut).replace(/[,:;—-]\s*$/, '') + '…';
}

function canonicalUrl(route, isZh = false) {
  if (route === '/') return isZh ? `${SITE}/zh/` : `${SITE}/`;
  return isZh ? `${SITE}/zh${route}` : `${SITE}${route}`;
}

function assetUrl(asset) {
  if (!asset) return `${SITE}/${DEFAULT_OG_IMAGE}`;
  if (/^https?:\/\//i.test(asset)) return asset;
  return `${SITE}/${String(asset).replace(/^\/+/, '')}`;
}

function jsonLdScript(data) {
  return `<script type="application/ld+json">\n${JSON.stringify(data, null, 2)}\n</script>`;
}

function breadcrumbJsonLd(route, items) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      item: canonicalUrl(item.route || route, false)
    }))
  };
}

function collectionJsonLd(route, title, description, itemRoutes = []) {
  return jsonLdScript({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'CollectionPage',
        '@id': `${canonicalUrl(route, false)}#collection`,
        url: canonicalUrl(route, false),
        name: title,
        description,
        isPartOf: { '@id': `${SITE}/#website` }
      },
      {
        '@type': 'ItemList',
        itemListElement: itemRoutes.slice(0, 50).map((item, index) => ({
          '@type': 'ListItem',
          position: index + 1,
          url: canonicalUrl(item.route, false),
          name: item.name
        }))
      },
      breadcrumbJsonLd(route, [
        { name: 'Home', route: '/' },
        { name: title, route }
      ])
    ]
  });
}

const STATIC_FAQS = {
  '/chinese-car-brands': [
    ['Which Chinese car brands sell internationally?', 'BYD, MG, Geely, Chery, Great Wall, NIO, Xpeng, Zeekr, Leapmotor and several sub-brands sell or prepare vehicles outside China, with coverage varying by market.'],
    ['What is the difference between Chinese legacy groups and EV startups?', 'Legacy groups such as BYD, Geely, SAIC, Chery and Great Wall have broad manufacturing and export networks, while startups such as NIO, Xpeng, Li Auto, Xiaomi and Leapmotor focus on newer EV, EREV and smart-car platforms.'],
    ['Which Chinese brands are strongest for export markets?', 'BYD, Chery, SAIC/MG, Geely and Great Wall have the broadest overseas footprints today, while NIO, Xpeng, Zeekr and Leapmotor are expanding selectively by region.']
  ],
  '/models': [
    ['Which Chinese EV models are most relevant for export markets?', 'BYD Seal, BYD Atto 3, MG4, Xiaomi SU7, Xpeng G6, Zeekr 001, NIO ET5 and Leapmotor C10 are among the models international buyers and dealers most often track.'],
    ['Are the prices listed on TopChinaCar export prices?', 'Model pages use indicative local list prices and approximate USD conversions. Actual export quotes depend on market, trim, homologation, logistics, taxes and exporter availability.'],
    ['Do Chinese EV specs differ by country?', 'Yes. Battery size, charging standard, safety equipment, software, warranty and homologation package can differ between China-market vehicles and export-market versions.']
  ],
  '/news': [
    ['What does TopChinaCar cover every day?', 'TopChinaCar tracks Chinese automakers overseas, EV and battery news, export data, overseas plants, dealer networks, tariffs, regulations and market-entry stories.'],
    ['Are TopChinaCar articles sourced?', 'Articles cite primary or reputable secondary sources inline and list source links where available, especially for data, policy and company announcements.'],
    ['Why focus on Chinese auto exports?', 'China has become the world’s largest car exporter, and export growth now shapes automaker strategy, global pricing, supply chains and policy debates.']
  ],
};

const STATIC_FAQS_ZH = {
  '/chinese-car-brands': [
    ['哪些中国汽车品牌正在海外销售？', '比亚迪、MG、吉利、奇瑞、长城、蔚来、小鹏、极氪、零跑及多个子品牌都在海外销售或准备进入海外市场，具体可售情况因地区而异。'],
    ['传统车企集团和造车新势力有什么区别？', '传统车企集团通常拥有更完整的制造和出口网络；新势力更多聚焦纯电、增程和智能化平台，软件迭代速度更快。'],
    ['哪些中国品牌的出口能力最强？', '比亚迪、奇瑞、上汽/MG、吉利和长城目前海外版图最广；蔚来、小鹏、极氪和零跑则按区域选择性扩张。']
  ],
  '/models': [
    ['哪些中国电动车最值得海外市场关注？', '比亚迪海豹、BYD Atto 3、MG4、小米 SU7、小鹏 G6、极氪 001、蔚来 ET5 和零跑 C10 是海外买家和经销商常关注的车型。'],
    ['TopChinaCar 上的价格是出口价吗？', '不是。车型页使用本地指导价和近似美元换算。实际出口报价取决于目的市场、配置、认证、物流、税费和出口商供货情况。'],
    ['中国电动车在不同国家的配置会不同吗？', '会。电池容量、充电标准、安全配置、软件、质保和认证包可能因中国版与出口版不同而变化。']
  ],
  '/news': [
    ['TopChinaCar 每天报道什么？', 'TopChinaCar 追踪中国车企出海、新能源与电池新闻、出口数据、海外工厂、经销网络、关税、监管和市场进入动态。'],
    ['TopChinaCar 的文章有信源吗？', '文章会在正文内引用一手或可信二手信源，尤其是涉及数据、政策和企业公告时，会尽量列出可核查链接。'],
    ['为什么重点关注中国汽车出口？', '中国已经成为全球第一大汽车出口国，出口增长正在影响车企战略、全球定价、供应链和政策讨论。']
  ],
};

function faqJsonLd(route, lang = 'en') {
  const items = (lang === 'zh' ? STATIC_FAQS_ZH : STATIC_FAQS)[route];
  if (!items) return '';
  return jsonLdScript({
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map(([q, a]) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: { '@type': 'Answer', text: a }
    }))
  });
}

function serviceJsonLd(route) {
  return '';
}

function pageHTML(route, meta, mainHTML, opts = {}) {
  const isZh = !!opts.zh;
  const enUrl = canonicalUrl(route, false);
  const zhUrl = canonicalUrl(route, true);
  const canonical = isZh ? zhUrl : enUrl;
  const ogImage = assetUrl(meta.image || opts.image || DEFAULT_OG_IMAGE);
  const altLinks = opts.noAlt ? '' : `<link rel="alternate" hreflang="en" href="${enUrl}" />
<link rel="alternate" hreflang="zh-CN" href="${zhUrl}" />
<link rel="alternate" hreflang="x-default" href="${enUrl}" />
`;
  const extraHead = opts.extraHead || meta.extraHead || '';
  meta = { ...meta, title: escAttr(truncateMeta(meta.title, 75)), desc: escAttr(truncateMeta(meta.desc, 165)) };
  return `<!DOCTYPE html>
<html lang="${isZh ? 'zh' : 'en'}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${meta.title}</title>
<meta name="description" content="${meta.desc}" />
${meta.robots ? `<meta name="robots" content="${escAttr(meta.robots)}" />\n` : ''}<meta name="author" content="TopChinaCar Editorial" />
<meta name="theme-color" content="#1a1a1a" />
<link rel="canonical" href="${canonical}" />
${altLinks}
<!-- Open Graph -->
<meta property="og:type" content="${meta.ogType || 'website'}" />
<meta property="og:site_name" content="TopChinaCar" />
<meta property="og:title" content="${meta.title}" />
<meta property="og:description" content="${meta.desc}" />
<meta property="og:url" content="${canonical}" />
<meta property="og:image" content="${ogImage}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:locale" content="${isZh ? 'zh_CN' : 'en_US'}" />
<meta property="og:locale:alternate" content="${isZh ? 'en_US' : 'zh_CN'}" />
${meta.published ? `<meta property="article:published_time" content="${meta.published}" />\n<meta property="article:section" content="China Auto Export" />` : ''}

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${meta.title}" />
<meta name="twitter:description" content="${meta.desc}" />
<meta name="twitter:image" content="${ogImage}" />

${route === '/' ? JSONLD + '\n' : ''}${extraHead ? extraHead + '\n' : ''}<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;0,700;0,900;1,500&family=Inter:wght@300;400;500;600;700&family=Noto+Serif+SC:wght@500;700;900&family=Noto+Sans+SC:wght@300;400;500;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/css/style.css" />
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' fill='%231a1a1a'/><text x='16' y='22' font-family='Playfair Display,serif' font-size='20' font-weight='900' text-anchor='middle' fill='%23d4302a'>T</text></svg>">
</head>
<body>

${headerHTML(route)}

<main id="app">${mainHTML}</main>

${NEWSLETTER}

${FOOTER}

<script src="/js/data.js?v=${BUILD_V}"></script>
<script src="/js/i18n.js?v=${BUILD_V}"></script>
<script src="/js/articles-data.js?v=${BUILD_V}"></script>
<script src="/js/pages.js?v=${BUILD_V}"></script>
<script src="/js/app.js?v=${BUILD_V}"></script>
</body>
</html>
`;
}

function staticCollectionItems(route) {
  if (route === '/chinese-car-brands') {
    return SITE_DATA.brands.map(b => ({ route: `/chinese-car-brands/${b.id}`, name: b.name }));
  }
  if (route === '/models') {
    return SITE_DATA.models.filter(m => m.id).map(m => ({ route: `/models/${m.id}`, name: `${m.brand} ${m.name}` }));
  }
  if (route === '/news') {
    return articles.map(a => ({ route: `/news/${a.slug}`, name: a.title_en }));
  }
  if (route === '/markets') {
    return MARKETS.map(m => ({ route: `/markets/${m.slug}`, name: m.name_en }));
  }
  return [];
}

function staticExtraHead(route, meta, lang = 'en') {
  if (meta.robots && meta.robots.includes('noindex')) return '';
  if (route === '/') return '';
  return [
    collectionJsonLd(route, meta.title.replace(/\s+\|\s+TopChinaCar$/, ''), meta.desc, staticCollectionItems(route)),
    faqJsonLd(route, lang),
    serviceJsonLd(route)
  ].filter(Boolean).join('\n');
}

// ---- Generate pages (EN + /zh mirror) ----
let count = 0;
for (const [route, meta] of Object.entries(PAGES)) {
  const mainHTML = PAGE_ROUTES[route]();
  fs.writeFileSync(path.join(ROOT, meta.file), pageHTML(route, { ...meta, extraHead: staticExtraHead(route, meta, 'en') }, mainHTML));
  setSandboxLang('zh');
  const mainZh = PAGE_ROUTES[route]();
  setSandboxLang('en');
  const zhMeta = PAGES_ZH[route] || meta;
  writeZh(meta.file, zhChrome(pageHTML(route, { ...zhMeta, extraHead: staticExtraHead(route, meta, 'zh') }, mainZh, { zh: true })));
  console.log(`✓ ${meta.file} + zh (${mainHTML.length} chars of prerendered content)`);
  count++;
}

// ---- Brand detail pages (/chinese-car-brands/<id>) ----
const BRANDS_OUT = path.join(ROOT, 'chinese-car-brands');
if (!fs.existsSync(BRANDS_OUT)) fs.mkdirSync(BRANDS_OUT);

const CATEGORY_LABEL = {
  group:    { en: 'Legacy Group', zh: '传统车企集团' },
  startup:  { en: 'New-Energy Startup', zh: '造车新势力' },
  subbrand: { en: 'Group Sub-Brand', zh: '集团子品牌' }
};

// Category-level buyer context (adds substance beyond the short brand blurb)
const CATEGORY_CONTEXT = {
  group: {
    en: 'As an established manufacturing group, it ships complete knock-down and fully-built vehicles worldwide, with mature homologation experience across left- and right-hand-drive markets. For dealers, that typically means broader spare-parts availability and factory-backed export documentation.',
    zh: '作为成熟的制造集团，其整车与 KD 件出口遍及全球，在左舵/右舵市场均有成熟的认证经验。对经销商而言，这通常意味着更完善的配件供应与厂家出口文件支持。'
  },
  startup: {
    en: 'As a new-energy startup, its lineup is EV-first with over-the-air software updates and rapid model cycles. Dealers importing these vehicles should verify charging-standard compatibility (CCS/GB-T) and local service arrangements for the destination market.',
    zh: '作为新势力车企，其产品以纯电为主，支持整车 OTA、车型迭代快。进口时需确认目的市场的充电标准兼容性（CCS/GB-T）与本地售后安排。'
  },
  subbrand: {
    en: 'It operates as an independent marque within its parent group, sharing platforms and the export network while targeting a distinct segment. Parts and homologation support generally flow through the parent group\'s international channels.',
    zh: '它作为母集团旗下的独立品牌运营，共享平台与出口网络，同时瞄准差异化细分市场。配件与认证支持通常通过母集团的国际渠道提供。'
  }
};

function langSpan(en, zh) {
  return `<span data-lang="en">${en}</span><span data-lang="zh" hidden>${zh}</span>`;
}

function brandMain(b) {
  const cat = CATEGORY_LABEL[b.category] || CATEGORY_LABEL.group;
  const ctx = CATEGORY_CONTEXT[b.category] || CATEGORY_CONTEXT.group;
  const models = SITE_DATA.models.filter(m => m.brand === b.name);
  const related = articles.filter(a =>
    (a.title_en + ' ' + (a.excerpt_en || '')).toLowerCase().includes(b.name.toLowerCase())).slice(0, 5);

  const fact = (labelEn, labelZh, val) => `
    <div class="brand-fact"><span class="spec-label">${langSpan(labelEn, labelZh)}</span><span class="spec-value">${val}</span></div>`;

  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">${langSpan(cat.en, cat.zh)}${b.parent_en ? ` · ${langSpan('Part of ' + b.parent_en, '隶属于' + (b.parent_zh || b.parent_en))}` : ''}</div>
      <h1 class="page-title">${b.name} <span style="font-size:.55em;color:#9ca3af;font-weight:500;">${b.cn}</span></h1>
      <p class="page-deck">${langSpan(b.desc_en, b.desc_zh)}</p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:920px;">
      <div class="brand-facts" style="display:flex;gap:36px;flex-wrap:wrap;margin-bottom:36px;">
        ${fact('Founded', '创立', b.founded)}
        ${fact('HQ', '总部', b.hq)}
        ${fact('Focus', '主攻', b.focus)}
        ${b.subBrands_en ? fact('Sub-brands', '旗下品牌', `${langSpan(b.subBrands_en, b.subBrands_zh || b.subBrands_en)}`) : ''}
      </div>
      <div style="font-size:16px;line-height:1.8;color:#374151;">
        <p>${langSpan(ctx.en, ctx.zh)}</p>
      </div>
      ${models.length ? `
      <h2 style="font-size:22px;margin:40px 0 20px;">${langSpan('Featured ' + b.name + ' models', b.name + ' 明星车型')}</h2>
      <div class="models-grid">
        ${models.map(m => modelCardHTML(m, 'en')).join('')}
      </div>` : ''}
      ${related.length ? `
      <h2 style="font-size:22px;margin:40px 0 20px;">${langSpan('Latest ' + b.name + ' news', b.name + ' 最新动态')}</h2>
      <ul style="list-style:none;padding:0;margin:0;">
        ${related.map(a => `<li style="margin-bottom:14px;"><a href="/news/${a.slug}" style="color:inherit;text-decoration:none;"><strong>${a.title_en}</strong></a><br/><span style="font-size:13px;color:#9ca3af;">${a.date}</span></li>`).join('')}
      </ul>` : ''}
      <p style="margin-top:40px;"><a href="/chinese-car-brands" style="color:var(--accent, #d4302a);font-family:var(--mono);font-size:13px;">← All 31 Chinese car brands</a></p>
    </div>
  </section>`;
}

function brandJsonLd(b) {
  return `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Brand",
      "name": "${b.name}",
      "alternateName": "${b.cn}",
      "url": "${SITE}/chinese-car-brands/${b.id}",
      "image": "${assetUrl(b.image)}",
      "description": ${JSON.stringify(b.desc_en)}
    },
    {
      "@type": "BreadcrumbList",
      "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Home", "item": "${SITE}/"},
        {"@type": "ListItem", "position": 2, "name": "Brands", "item": "${SITE}/chinese-car-brands"},
        {"@type": "ListItem", "position": 3, "name": "${b.name}", "item": "${SITE}/chinese-car-brands/${b.id}"}
      ]
    }
  ]
}
</script>`;
}

// ---- Brand auto-linker: first mention of each brand in article text → /chinese-car-brands/<id> ----
// Works on HTML strings; skips text inside <a>…</a> and headings.
function linkifyBrands(html, lang) {
  if (!html) return html;
  const done = new Set();
  const segments = html.split(/(<[^>]+>)/);
  let skipDepth = 0;
  const brands = [...SITE_DATA.brands].sort((x, y) => y.name.length - x.name.length);
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    if (seg.startsWith('<')) {
      if (/^<(a|h[1-6])[\s>]/i.test(seg)) skipDepth++;
      else if (/^<\/(a|h[1-6])>/i.test(seg)) skipDepth = Math.max(0, skipDepth - 1);
      continue;
    }
    if (skipDepth > 0 || !seg.trim()) continue;
    let text = seg;
    for (const b of brands) {
      if (done.has(b.id)) continue;
      const needle = lang === 'zh' ? b.cn : b.name;
      if (!needle) continue;
      let idx = -1;
      if (lang === 'zh') {
        idx = text.indexOf(needle);
      } else {
        const re = new RegExp('\\b' + needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b');
        const m2 = text.match(re);
        idx = m2 ? m2.index : -1;
      }
      if (idx === -1) continue;
      text = text.slice(0, idx)
        + `<a href="/chinese-car-brands/${b.id}" style="color:inherit;text-decoration:underline;text-decoration-color:#d4302a;text-underline-offset:3px;">${needle}</a>`
        + text.slice(idx + needle.length);
      done.add(b.id);
    }
    segments[i] = text;
  }
  return segments.join('');
}


const modelCardHTML = vm.runInContext('modelCardHTML', sandbox);
for (const b of SITE_DATA.brands) {
  const catEn = (CATEGORY_LABEL[b.category] || CATEGORY_LABEL.group).en;
  const main = brandMain(b);
  const html = pageHTML(`/chinese-car-brands/${b.id}`, {
    title: `${b.name} (${b.cn}): Models, Sub-brands & Global Footprint | TopChinaCar`,
    desc: `${b.desc_en} ${catEn}, founded ${b.founded}, HQ ${b.hq} — brand profile, featured models and export news.`,
    image: b.image
  }, main).replace('</head>', brandJsonLd(b) + '\n</head>');
  fs.writeFileSync(path.join(BRANDS_OUT, `${b.id}.html`), html);
  writeZh(`chinese-car-brands/${b.id}.html`, zhChrome(pageHTML(`/chinese-car-brands/${b.id}`, {
    title: `${b.name}（${b.cn}）：车型、子品牌与全球布局 | TopChinaCar`,
    desc: `${b.desc_zh} 创立于 ${b.founded}，总部 ${b.hq}——品牌档案、明星车型与最新出海动态。`,
    image: b.image
  }, main, { zh: true }).replace('</head>', brandJsonLd(b) + '\n</head>')));
}
console.log(`✓ ${SITE_DATA.brands.length} brand pages → brands/ + zh/chinese-car-brands/`);

// ---- Model detail pages (/models/<id>) ----
const MODELS_OUT = path.join(ROOT, 'models');
if (!fs.existsSync(MODELS_OUT)) fs.mkdirSync(MODELS_OUT);

function modelMain(m, brand) {
  const cat = brand ? (CATEGORY_LABEL[brand.category] || CATEGORY_LABEL.group) : CATEGORY_LABEL.group;
  const ctx = brand ? (CATEGORY_CONTEXT[brand.category] || CATEGORY_CONTEXT.group) : CATEGORY_CONTEXT.group;
  const related = articles.filter(a =>
    (a.title_en + ' ' + (a.excerpt_en || '')).toLowerCase().includes(m.brand.toLowerCase())
    || (a.title_en + ' ' + (a.excerpt_en || '')).toLowerCase().includes(m.name.toLowerCase())).slice(0, 5);
  const siblings = SITE_DATA.models.filter(x => x.brand === m.brand && x.id !== m.id);
  const fact = (labelEn, labelZh, val) => `
    <div class="brand-fact"><span class="spec-label">${langSpan(labelEn, labelZh)}</span><span class="spec-value">${val}</span></div>`;
  const visual = m.image
    ? `<div style="margin:0 0 32px;border-radius:12px;overflow:hidden;position:relative;"><img src="/${m.image}" alt="${m.brand} ${m.name}" style="width:100%;display:block;" />${m.imageCredit ? `<span class="img-credit">Photo: ${m.imageCredit}</span>` : ''}</div>`
    : '';
  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">${brand ? `<a href="/chinese-car-brands/${brand.id}" style="color:inherit;text-decoration:none;">${m.brand}</a>` : m.brand} · ${langSpan(cat.en, cat.zh)}</div>
      <h1 class="page-title">${m.brand} ${m.name}</h1>
      <p class="page-deck">${langSpan(m.tag_en, m.tag_zh)}</p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:920px;">
      ${visual}
      <div class="brand-facts" style="display:flex;gap:36px;flex-wrap:wrap;margin-bottom:36px;">
        ${fact('Range', '续航', m.range)}
        ${fact('0–100 km/h', '零百加速', m.accel)}
        ${fact('From', '起价', `${m.price}${m.priceLocal ? ` <span style="font-size:12px;color:#9ca3af;font-weight:400;">(${m.priceLocal})</span>` : ''}`)}
      </div>
      <div style="font-size:16px;line-height:1.8;color:#374151;">
        <p>${langSpan(ctx.en, ctx.zh)}</p>
        <p style="font-size:13px;color:#9ca3af;">${langSpan(
          'USD figures are approximate conversions of the local list price shown in brackets, and move with exchange rates and market promotions.',
          '美元价格为括号内当地指导价的近似换算，随汇率与市场优惠波动。')}</p>
      </div>
      ${siblings.length ? `
      <h2 style="font-size:22px;margin:40px 0 20px;">${langSpan('More ' + m.brand + ' models', m.brand + ' 其他车型')}</h2>
      <ul style="list-style:none;padding:0;margin:0;">
        ${siblings.map(s => `<li style="margin-bottom:10px;"><a href="/models/${s.id}" style="color:inherit;text-decoration:none;"><strong>${s.brand} ${s.name}</strong></a> <span style="font-size:13px;color:#9ca3af;">· ${s.range} · ${s.price}</span></li>`).join('')}
      </ul>` : ''}
      ${related.length ? `
      <h2 style="font-size:22px;margin:40px 0 20px;">${langSpan('Related news', '相关动态')}</h2>
      <ul style="list-style:none;padding:0;margin:0;">
        ${related.map(a => `<li style="margin-bottom:14px;"><a href="/news/${a.slug}" style="color:inherit;text-decoration:none;"><strong>${a.title_en}</strong></a><br/><span style="font-size:13px;color:#9ca3af;">${a.date}</span></li>`).join('')}
      </ul>` : ''}
      <p style="margin-top:40px;">
        ${brand ? `<a href="/chinese-car-brands/${brand.id}" style="color:var(--accent, #d4302a);font-family:var(--mono);font-size:13px;">← ${m.brand} brand profile</a> · ` : ''}
        <a href="/models" style="color:var(--accent, #d4302a);font-family:var(--mono);font-size:13px;">← All featured models</a>
      </p>
    </div>
  </section>`;
}

function modelJsonLd(m) {
  return `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Product",
      "name": "${m.brand} ${m.name}",
      "brand": {"@type": "Brand", "name": "${m.brand}"},
      "url": "${SITE}/models/${m.id}",
      "image": "${assetUrl(m.image)}",
      "description": ${JSON.stringify(m.tag_en)},
      "category": "Vehicle"
    },
    {
      "@type": "BreadcrumbList",
      "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Home", "item": "${SITE}/"},
        {"@type": "ListItem", "position": 2, "name": "Models", "item": "${SITE}/models"},
        {"@type": "ListItem", "position": 3, "name": "${m.brand} ${m.name}", "item": "${SITE}/models/${m.id}"}
      ]
    }
  ]
}
</script>`;
}

let modelCount = 0;
for (const m of SITE_DATA.models) {
  if (!m.id) continue;
  const brand = SITE_DATA.brands.find(b => b.name === m.brand);
  const main = modelMain(m, brand);
  const html = pageHTML(`/models/${m.id}`, {
    title: `${m.brand} ${m.name}: Specs, Range & Price | TopChinaCar`,
    desc: `${m.tag_en} Range ${m.range}, 0-100 km/h ${m.accel}, from ${m.price} — specs, pricing and export-market context.`,
    image: m.image
  }, main).replace('</head>', modelJsonLd(m) + '\n</head>');
  fs.writeFileSync(path.join(MODELS_OUT, `${m.id}.html`), html);
  writeZh(`models/${m.id}.html`, zhChrome(pageHTML(`/models/${m.id}`, {
    title: `${m.brand} ${m.name} 参数、续航与价格 | TopChinaCar`,
    desc: `${m.tag_zh} 续航 ${m.range}，零百加速 ${m.accel}，${m.price} 起——参数、价格与出口市场背景。`,
    image: m.image
  }, main, { zh: true }).replace('</head>', modelJsonLd(m) + '\n</head>')));
  modelCount++;
}
console.log(`✓ ${modelCount} model pages → models/ + zh/models/`);

// ============ SECTION PAGES (news-site taxonomy) ============
// Articles are matched to sections by keyword — until the pipeline tags them natively.
const SECTIONS = [
  {
    route: '/china-ev-news', file: 'china-ev-news.html',
    title_en: 'China EV News — Electric Vehicles, Batteries & Smart Cars | TopChinaCar',
    title_zh: '中国新能源车新闻 — 电动车、电池与智能汽车 | TopChinaCar',
    h1_en: 'China EV News', h1_zh: '中国新能源车新闻',
    deck_en: 'Electric vehicles, plug-in hybrids, EREVs, batteries, charging and smart-driving — the technology side of China’s auto globalization.',
    deck_zh: '追踪中国纯电、插混、增程、电池、补能与智能驾驶进展，解释这些技术如何影响中国汽车全球化。',
    intro_en: 'China builds and exports more electric vehicles than any other country. This section tracks the products and technologies behind that lead: new EV, PHEV and EREV launches relevant to overseas markets, battery and charging developments, and the smart-driving and cockpit systems that increasingly differentiate Chinese cars abroad.',
    intro_zh: '中国是全球最大的电动车生产国和出口国。本栏目追踪这一领先地位背后的产品与技术：与海外市场相关的纯电、插混、增程新车，电池与补能进展，以及日益成为中国汽车海外差异化优势的智驾与座舱系统。',
    kw: /\bEVs?\b|electric|battery|batteries|PHEV|EREV|plug-in|hybrid|charging|swap|autonomous|smart driving|ADAS|\bNEV/i
  },
  {
    route: '/china-car-export-news', file: 'china-car-export-news.html',
    title_en: 'China Car Export News — Shipments, Plants & Overseas Growth | TopChinaCar',
    title_zh: '中国汽车出口新闻 — 出口数据、海外工厂与增长 | TopChinaCar',
    h1_en: 'China Car Export News', h1_zh: '中国汽车出口新闻',
    deck_en: 'Monthly export figures, overseas plants, dealer networks, logistics and homologation — how Chinese cars reach the world.',
    deck_zh: '追踪中国汽车月度出口数据、海外工厂、经销商网络、物流与认证，解释中国汽车如何进入全球市场。',
    intro_en: 'China became the world’s largest car exporter by volume, and the export machine keeps evolving: from shipping fully-built vehicles to building plants in Thailand, Brazil, Hungary and Spain. This section follows the numbers, the factories, the dealer networks, and the fuel-mix of what actually gets exported — ICE, hybrid and electric.',
    intro_zh: '中国已成为全球第一大汽车出口国，而且出海模式仍在进化：从整车出口到在泰国、巴西、匈牙利、西班牙建厂。本栏目跟踪出口数据、海外工厂、经销网络，以及实际出口的燃油/混动/纯电结构。',
    kw: /export|overseas|shipment|ro-ro|plant|factory|localis|localiz|assembl|dealer network|knock-down/i
  },
  {
    route: '/markets', file: 'markets.html',
    title_en: 'Global Markets — Where Chinese Cars Are Expanding | TopChinaCar',
    title_zh: '全球市场 — 中国汽车的海外扩张版图 | TopChinaCar',
    h1_en: 'Global Markets', h1_zh: '全球市场',
    deck_en: 'Market-by-market coverage of Chinese auto expansion — Europe, the Middle East, Africa, Latin America, Southeast Asia and Australia.',
    deck_zh: '逐个市场追踪中国汽车的海外扩张路径，覆盖欧洲、中东、非洲、拉美、东南亚与澳洲等重点区域。',
    intro_en: 'Chinese automakers do not expand everywhere the same way: Europe means tariffs and localisation, the Gulf means rapid brand adoption, Latin America means plants and pickups, Southeast Asia means right-hand-drive EV hubs. Pick a market below to follow the coverage.',
    intro_zh: '中国车企在不同市场的打法完全不同：欧洲是关税与本地化，海湾是品牌快速渗透，拉美是建厂与皮卡，东南亚是右舵电动车枢纽。选择下方市场查看对应报道。',
    kw: /Europe|EU\b|Middle East|Gulf|Saudi|UAE|Dubai|Africa|Latin America|Brazil|Mexico|Chile|Thailand|Indonesia|Malaysia|Vietnam|Australia|Russia|Central Asia/i,
    isMarketsIndex: true
  },
  {
    route: '/policy', file: 'policy.html',
    title_en: 'Policy & Tariffs — Rules Shaping China Auto Exports | TopChinaCar',
    title_zh: '政策与关税 — 影响中国汽车出口的规则 | TopChinaCar',
    h1_en: 'Policy & Tariffs', h1_zh: '政策与关税',
    deck_en: 'EU tariffs, US restrictions, homologation, subsidies — the regulatory forces shaping where Chinese cars can go.',
    deck_zh: '解读欧盟关税、美国限制、海外认证与补贴政策，追踪决定中国汽车能去哪里的监管力量。',
    intro_en: 'Trade policy is now the single biggest variable in China auto globalization. EU anti-subsidy duties pushed Chinese brands toward European plants; US rules effectively closed one market while opening questions about Mexico; certification regimes decide launch timelines everywhere. This section tracks the rules and what automakers do about them.',
    intro_zh: '贸易政策已成为中国汽车全球化的最大变量。欧盟反补贴税把中国品牌推向欧洲建厂；美国规则实际关闭了一个市场；各国认证体系决定上市节奏。本栏目追踪规则本身，以及车企的应对。',
    kw: /tariff|policy|regulat|subsid|homologation|sanction|trade|duty|duties|ban\b|restriction/i
  },
  {
    route: '/data', file: 'data.html',
    title_en: 'Data & Rankings — China Auto Export & Sales Data | TopChinaCar',
    title_zh: '数据与排名 — 中国汽车出口与销量数据 | TopChinaCar',
    h1_en: 'Data & Rankings', h1_zh: '数据与排名',
    deck_en: 'Export volumes, brand rankings, market share and model data — the numbers behind the headlines.',
    deck_zh: '汇总中国汽车出口量、品牌排名、市场份额与车型参数数据，用数字解释行业新闻背后的真实趋势。',
    intro_en: 'Every story on TopChinaCar is grounded in numbers: monthly export and delivery figures, brand-by-brand overseas share, and model-level specs and pricing. This section collects data-led coverage, plus our reference model database with specs and indicative prices in USD.',
    intro_zh: 'TopChinaCar 的每篇报道都以数字为底：月度出口与交付数据、各品牌海外占比、车型级参数与价格。本栏目汇总数据向报道，并提供以美元计价的参考车型数据库。',
    kw: /sales|deliver|units|record|ranking|market share|figure|\bH[12]\b|\bQ[1-4]\b|million|\d{2,3},\d{3}/i,
    extra_en: '<p style="margin:18px 0 0;"><a href="/models" style="color:var(--accent, #d4302a);font-family:var(--mono, monospace);font-size:13px;">→ Model database: 42 Chinese models with specs & USD pricing</a></p>',
    extra_zh: '<p style="margin:18px 0 0;"><a href="/models" style="color:var(--accent, #d4302a);font-family:var(--mono, monospace);font-size:13px;">→ 车型数据库：42 款中国车型的参数与美元价格</a></p>'
  },
  {
    route: '/analysis', file: 'analysis.html',
    title_en: 'Analysis — China Auto Globalization Explained | TopChinaCar',
    title_zh: '深度分析 — 解读中国汽车全球化 | TopChinaCar',
    h1_en: 'Analysis', h1_zh: '深度分析',
    deck_en: 'Longer reads on why, how and where Chinese automakers are going global.',
    deck_zh: '提供中国车企为什么出海、如何出海、去哪里的长篇解读，关注战略、供应链、商业模式与全球竞争。',
    intro_en: 'Beyond the daily news cycle: structural pieces on supply chains, business models and strategy that explain China auto globalization to international readers.',
    intro_zh: '跳出每日新闻循环：从供应链、商业模式与战略层面，向国际读者解释中国汽车全球化的结构性文章。',
    kw: /strategy|why |analysis|explained|model\b.*global/i,
    showStories: true
  }
];

const MARKETS = [
  { slug: 'europe', name_en: 'Europe', name_zh: '欧洲',
    kw: /Europe|\bEU\b|Germany|France|Spain|Italy|UK\b|Britain|Norway|Netherlands|Hungary|Munich|Zaragoza|Poland|Belgium/i,
    intro_en: 'Europe is the highest-stakes market for Chinese automakers: big EV demand, strong incumbent brands, and anti-subsidy tariffs that have pushed BYD, Chery, Leapmotor and others toward local production in Hungary, Spain and beyond. MG remains the best-selling Chinese badge; premium EV brands test the waters from Norway outward.',
    intro_zh: '欧洲是中国车企风险与回报最高的市场：电动车需求大、本土品牌强势，反补贴关税正把比亚迪、奇瑞、零跑等推向匈牙利、西班牙等地的本地化生产。MG 仍是销量最高的中国血统品牌，高端电动品牌则从挪威开始试水。' },
  { slug: 'middle-east', name_en: 'Middle East', name_zh: '中东',
    kw: /Middle East|Gulf|Saudi|UAE|Dubai|Qatar|Kuwait|Oman|Bahrain|Israel|GCC/i,
    intro_en: 'The Gulf has become one of the fastest-adopting regions for Chinese cars — ICE SUVs first, EVs increasingly. Chery, GWM, BYD and MG all run growing dealer networks, and Dubai doubles as a re-export hub for the wider region.',
    intro_zh: '海湾地区已成为中国汽车渗透最快的区域之一——先是燃油 SUV，如今电动车加速跟进。奇瑞、长城、比亚迪、MG 的经销网络都在扩张，迪拜还是面向更大区域的转口枢纽。' },
  { slug: 'saudi-arabia', name_en: 'Saudi Arabia', name_zh: '沙特阿拉伯',
    kw: /Saudi|Riyadh|Jeddah|KSA/i,
    intro_en: 'Saudi Arabia is the largest Gulf car market and a priority for Chinese brands, with rapid share gains in SUVs and growing EV ambitions tied to Vision 2030.',
    intro_zh: '沙特是海湾最大的汽车市场，也是中国品牌的优先目标：SUV 份额快速攀升，电动化雄心与 2030 愿景绑定。' },
  { slug: 'uae', name_en: 'UAE', name_zh: '阿联酋',
    kw: /UAE|Dubai|Abu Dhabi|Emirates/i,
    intro_en: 'The UAE combines a wealthy domestic market with Dubai’s role as the region’s trading hub — many Chinese brands stage their Middle East entry, flagship showrooms and regional distribution here.',
    intro_zh: '阿联酋既有高消费本地市场，又有迪拜的区域贸易枢纽角色——许多中国品牌把中东首发、旗舰展厅与区域分销放在这里。' },
  { slug: 'africa', name_en: 'Africa', name_zh: '非洲',
    kw: /Africa|South Africa|Egypt|Nigeria|Morocco|Kenya|Algeria|Rosslyn/i,
    intro_en: 'Africa is a pickup, SUV and commercial-vehicle story for Chinese automakers, with South Africa as the anchor market and local assembly beginning to take root.',
    intro_zh: '在非洲，中国汽车的故事以皮卡、SUV 与商用车为主线，南非是锚点市场，本地组装也开始落地。' },
  { slug: 'latin-america', name_en: 'Latin America', name_zh: '拉丁美洲',
    kw: /Latin America|LatAm|Mexico|Chile|Colombia|Peru|Uruguay|Argentina/i,
    intro_en: 'Latin America took Chinese brands early — Chery has deep roots here — and is now a localisation frontier, with plants and CKD assembly spreading from Brazil outward.',
    intro_zh: '拉美很早就接纳了中国品牌——奇瑞在此根基深厚——如今正成为本地化前线，工厂与 CKD 组装从巴西向外扩散。' },
  { slug: 'brazil', name_en: 'Brazil', name_zh: '巴西',
    kw: /Brazil|Bahia|Camaçari|São Paulo|Horizonte|Iracemápolis|Ayrton Senna/i,
    intro_en: 'Brazil is Latin America’s biggest market and the region’s manufacturing prize: BYD, GWM and SAIC are all investing in local production to serve the country and export across South America.',
    intro_zh: '巴西是拉美最大市场，也是区域制造高地：比亚迪、长城、上汽都在投资本地生产，既供应巴西也辐射南美。' },
  { slug: 'southeast-asia', name_en: 'Southeast Asia', name_zh: '东南亚',
    kw: /Southeast Asia|Thailand|Indonesia|Malaysia|Vietnam|Philippines|Singapore|ASEAN|Melaka|Proton/i,
    intro_en: 'Southeast Asia is China’s right-hand-drive EV workshop: Thailand and Indonesia host a cluster of Chinese plants that serve ASEAN and increasingly export onward — including to Europe.',
    intro_zh: '东南亚是中国车企的右舵电动车工坊：泰国与印尼聚集了一批中国工厂，供应东盟并日益向外出口——包括欧洲。' },
  { slug: 'australia', name_en: 'Australia', name_zh: '澳大利亚',
    kw: /Australia|New Zealand|Sydney|Melbourne/i,
    intro_en: 'Australia is one of the most open right-hand-drive markets, where GWM, MG and BYD already sit among the top-selling brands and PHEV utes are the new battleground.',
    intro_zh: '澳大利亚是最开放的右舵市场之一，长城、MG、比亚迪已跻身畅销品牌之列，插混皮卡是新战场。' }
];

function articleListHTML(list, emptyEn, emptyZh) {
  if (!list.length) {
    return `<p style="color:#6b7280;font-size:15px;">${langSpan(emptyEn, emptyZh)} <a href="/news" style="color:var(--accent, #d4302a);">${langSpan('Browse all news →', '浏览全部新闻 →')}</a></p>`;
  }
  return `<ul style="list-style:none;padding:0;margin:0;">
    ${list.map(a => `<li style="margin-bottom:20px;padding-bottom:20px;border-bottom:1px solid #f3f4f6;">
      <div style="font-family:var(--mono, monospace);font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#dc2626;margin-bottom:6px;">${a.date}</div>
      <a href="/news/${a.slug}" style="color:inherit;text-decoration:none;"><strong style="font-family:var(--serif, Georgia, serif);font-size:19px;line-height:1.35;">${langSpan(a.title_en, a.title_zh || a.title_en)}</strong></a>
      <p style="margin:6px 0 0;font-size:14px;color:#6b7280;line-height:1.6;">${langSpan(a.excerpt_en || '', a.excerpt_zh || a.excerpt_en || '')}</p>
    </li>`).join('\n    ')}
  </ul>`;
}

function sectionNavHTML(current) {
  return `<div style="margin-top:44px;padding-top:20px;border-top:1px solid #e5e7eb;font-size:13px;font-family:var(--mono, monospace);">
    <span style="color:#9ca3af;letter-spacing:.12em;text-transform:uppercase;">${langSpan('Sections', '栏目')}:</span>
    ${SECTIONS.filter(s => s.route !== current).map(s => `<a href="${s.route}" style="color:var(--accent, #d4302a);text-decoration:none;margin-left:14px;">${langSpan(s.h1_en, s.h1_zh)}</a>`).join('')}
  </div>`;
}

function sectionMain(sec) {
  const matched = articles.filter(a => sec.kw.test(`${a.title_en} ${a.excerpt_en || ''}`)).slice(0, 20);
  const marketsGrid = sec.isMarketsIndex ? `
    <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:16px;margin:32px 0;">
      ${MARKETS.map(mk => `
      <a href="/markets/${mk.slug}" style="display:block;padding:20px 22px;border:1px solid #e5e7eb;border-radius:10px;color:inherit;text-decoration:none;background:#fff;">
        <strong style="font-family:var(--serif, Georgia, serif);font-size:19px;">${langSpan(mk.name_en, mk.name_zh)}</strong>
        <p style="margin:8px 0 0;font-size:13px;color:#6b7280;line-height:1.6;">${langSpan(mk.intro_en.split('. ')[0].slice(0, 110) + '…', mk.intro_zh.split('。')[0].slice(0, 60) + '…')}</p>
      </a>`).join('')}
    </div>` : '';
  const storiesList = sec.showStories && SITE_STORIES.length ? `
    <h2 style="font-size:22px;margin:36px 0 18px;">${langSpan('Feature stories', '深度故事')}</h2>
    <ul style="list-style:none;padding:0;margin:0 0 36px;">
      ${SITE_STORIES.map(s => {
        const f = (SITE_DATA.features || []).find(x => x.slug === s.slug) || {};
        return `<li style="margin-bottom:16px;"><a href="/stories/${s.slug}" style="color:inherit;text-decoration:none;"><strong style="font-family:var(--serif, Georgia, serif);font-size:19px;">${langSpan(f.title_en || s.slug, f.title_zh || f.title_en || s.slug)}</strong></a><p style="margin:4px 0 0;font-size:14px;color:#6b7280;">${langSpan(f.desc_en || '', f.desc_zh || '')}</p></li>`;
      }).join('\n      ')}
    </ul>` : '';
  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">${langSpan('Section', '栏目')}</div>
      <h1 class="page-title">${langSpan(sec.h1_en, sec.h1_zh)}</h1>
      <p class="page-deck">${langSpan(sec.deck_en, sec.deck_zh)}</p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:880px;">
      <p style="font-size:16px;line-height:1.8;color:#374151;margin:0 0 28px;">${langSpan(sec.intro_en, sec.intro_zh)}</p>
      ${sec.extra_en ? langSpan(sec.extra_en, sec.extra_zh || sec.extra_en) : ''}
      ${marketsGrid}
      ${storiesList}
      <h2 style="font-size:22px;margin:36px 0 18px;">${langSpan('Latest coverage', '最新报道')}</h2>
      ${articleListHTML(matched, 'Dedicated coverage for this section is ramping up — the Daily Briefing covers these topics every weekday.', '本栏目的专题报道正在积累中——每日简报每个工作日都覆盖相关主题。')}
      ${sectionNavHTML(sec.route)}
    </div>
  </section>`;
}

for (const sec of SECTIONS) {
  const main = sectionMain(sec);
  const sectionItems = articles
    .filter(a => sec.kw.test(`${a.title_en} ${a.excerpt_en || ''}`))
    .map(a => ({ route: `/news/${a.slug}`, name: a.title_en }));
  const meta = {
    title: sec.title_en,
    desc: sec.deck_en,
    extraHead: collectionJsonLd(sec.route, sec.h1_en, sec.deck_en, sec.isMarketsIndex
      ? MARKETS.map(m => ({ route: `/markets/${m.slug}`, name: m.name_en }))
      : sectionItems)
  };
  fs.writeFileSync(path.join(ROOT, sec.file),
    pageHTML(sec.route, meta, main));
  writeZh(sec.file, zhChrome(pageHTML(sec.route, { title: sec.title_zh, desc: sec.deck_zh, extraHead: meta.extraHead }, main, { zh: true })));
}
console.log(`✓ ${SECTIONS.length} section pages (+zh)`);

// ---- Market pages (/markets/<slug>) ----
const MARKETS_OUT = path.join(ROOT, 'markets');
if (!fs.existsSync(MARKETS_OUT)) fs.mkdirSync(MARKETS_OUT);
for (const mk of MARKETS) {
  const matched = articles.filter(a => mk.kw.test(`${a.title_en} ${a.excerpt_en || ''}`)).slice(0, 20);
  const main = `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow"><a href="/markets" style="color:inherit;text-decoration:none;">${langSpan('Markets', '市场')}</a></div>
      <h1 class="page-title">${langSpan('Chinese Cars in ' + mk.name_en, mk.name_zh + '：中国汽车市场观察')}</h1>
      <p class="page-deck">${langSpan(mk.intro_en.split('. ')[0] + '.', mk.intro_zh.split('。')[0] + '。')}</p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:880px;">
      <p style="font-size:16px;line-height:1.8;color:#374151;margin:0 0 28px;">${langSpan(mk.intro_en, mk.intro_zh)}</p>
      <h2 style="font-size:22px;margin:36px 0 18px;">${langSpan('Latest coverage', '最新报道')}</h2>
      ${articleListHTML(matched, `Market-specific coverage of ${mk.name_en} is ramping up.`, `${mk.name_zh}市场的专题报道正在积累中。`)}
      <p style="margin-top:36px;"><a href="/markets" style="color:var(--accent, #d4302a);font-family:var(--mono);font-size:13px;">← All markets</a></p>
    </div>
  </section>`;
  const metaEn = {
    title: `Chinese Cars in ${mk.name_en} — Brands, EVs & Market News | TopChinaCar`,
    desc: mk.intro_en,
    extraHead: collectionJsonLd(`/markets/${mk.slug}`, `Chinese Cars in ${mk.name_en}`, mk.intro_en,
      matched.map(a => ({ route: `/news/${a.slug}`, name: a.title_en })))
  };
  fs.writeFileSync(path.join(MARKETS_OUT, `${mk.slug}.html`),
    pageHTML(`/markets/${mk.slug}`, metaEn, main));
  writeZh(`markets/${mk.slug}.html`, zhChrome(pageHTML(`/markets/${mk.slug}`, {
    title: `${mk.name_zh}中国汽车市场 — 品牌、电动车与市场动态 | TopChinaCar`,
    desc: mk.intro_zh,
    extraHead: metaEn.extraHead
  }, main, { zh: true })));
}
console.log(`✓ ${MARKETS.length} market pages (+zh)`);

// ---- Feature story pages (/stories/<slug>) ----
const STORIES_OUT = path.join(ROOT, 'stories');
if (!fs.existsSync(STORIES_OUT)) fs.mkdirSync(STORIES_OUT);

function storyMain(f, s) {
  const langBlock = (lang, html) => `<div data-lang="${lang}"${lang === 'zh' ? ' hidden' : ''}>${linkifyBrands(html, lang)}</div>`;
  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">${langSpan(f.tag_en, f.tag_zh)} · ${langSpan(f.meta_en, f.meta_zh)}</div>
      <h1 class="page-title">${langSpan(f.title_en, f.title_zh)}</h1>
      <p class="page-deck">${langSpan(f.desc_en, f.desc_zh)}</p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:820px;">
      ${bylineHTML(new Date(s.date + 'T00:00:00Z').toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' }), s.date)}
      ${f.image ? `<div style="margin:0 0 36px;border-radius:12px;overflow:hidden;position:relative;"><img src="/${f.image}" alt="${f.title_en}" style="width:100%;display:block;" />${f.imageCredit ? `<span class="img-credit">Photo: ${f.imageCredit}</span>` : ''}</div>` : ''}
      <article class="article-body" style="font-size:16px;line-height:1.8;">
        ${langBlock('en', s.html_en)}
        ${langBlock('zh', s.html_zh || s.html_en)}
      </article>
      <p style="margin-top:32px;"><a href="/news" style="color:var(--accent);font-family:var(--mono);font-size:13px;">← All news & features</a></p>
    </div>
  </section>`;
}

function storyJsonLd(f, s) {
  return `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "headline": ${JSON.stringify(f.title_en)},
  "description": ${JSON.stringify(f.desc_en)},
  "datePublished": "${s.date}",
  "dateModified": "${s.date}",
  "image": "${assetUrl(f.image)}",
  "inLanguage": ["en", "zh-CN"],
  "mainEntityOfPage": "${SITE}/stories/${f.slug}",
  "author": {"@type": "Organization", "name": "TopChinaCar", "url": "${SITE}/"},
  "publisher": {"@id": "${SITE}/#organization"}
}
</script>`;
}

let storyCount = 0;
for (const s of SITE_STORIES) {
  const f = (SITE_DATA.features || []).find(x => x.slug === s.slug);
  if (!f) { console.error(`✗ story ${s.slug} has no matching features[] entry — skipped`); continue; }
  const main = storyMain(f, s);
  const html = pageHTML(`/stories/${f.slug}`, {
    title: `${f.title_en} | TopChinaCar`,
    desc: f.desc_en,
    image: f.image,
    ogType: 'article',
    published: s.date
  }, main).replace('</head>', storyJsonLd(f, s) + '\n</head>');
  fs.writeFileSync(path.join(STORIES_OUT, `${f.slug}.html`), html);
  writeZh(`stories/${f.slug}.html`, zhChrome(pageHTML(`/stories/${f.slug}`, {
    title: `${f.title_zh} | TopChinaCar`,
    desc: f.desc_zh,
    image: f.image,
    ogType: 'article',
    published: s.date
  }, main, { zh: true }).replace('</head>', storyJsonLd(f, s) + '\n</head>')));
  storyCount++;
}
if (storyCount) console.log(`✓ ${storyCount} feature stories → stories/ + zh/stories/`);

// ---- Daily article pages (/news/<slug>) ----
const NEWS_OUT = path.join(ROOT, 'news');
if (!fs.existsSync(NEWS_OUT)) fs.mkdirSync(NEWS_OUT);
// Extract unique external sources (href + label) from article HTML
function extractSources(html) {
  const seen = new Set(); const out = [];
  for (const m of (html || '').matchAll(/<a href="(https?:\/\/[^"]+)">\[?([^<\]]+)\]?<\/a>/g)) {
    if (seen.has(m[1])) continue;
    seen.add(m[1]);
    let host = '';
    try { host = new URL(m[1]).hostname.replace(/^www\./, ''); } catch (e) {}
    out.push({ url: m[1], label: m[2].trim(), host });
  }
  return out.slice(0, 25);
}

function sourcesBlockHTML(sources) {
  if (!sources.length) return '';
  return `
      <div style="margin-top:40px;padding-top:24px;border-top:1px solid #e5e7eb;">
        <h2 style="font-size:16px;margin:0 0 12px;">${langSpan('Sources', '信息来源')}</h2>
        <ul style="list-style:none;padding:0;margin:0;font-size:13px;line-height:1.9;color:#6b7280;">
          ${sources.map(s => `<li><a href="${s.url}" rel="noopener" target="_blank" style="color:inherit;">${s.label}</a> <span style="color:#9ca3af;">· ${s.host}</span></li>`).join('\n          ')}
        </ul>
      </div>`;
}

function bylineHTML(dateNice, dateIso) {
  return `
      <div style="display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:0 0 28px;font-family:var(--mono, monospace);font-size:12px;letter-spacing:.06em;color:#6b7280;">
        <span>${langSpan('By TopChinaCar Editorial', '作者：TopChinaCar 编辑部')}</span>
        <span>·</span>
        <span>${langSpan('Published ' + dateNice, '发布于 ' + dateIso)}</span>
        <span>·</span>
        <span>${langSpan('Compiled from the primary sources cited below', '基于文末所列一手信源编写')}</span>
      </div>`;
}

function articleMain(a) {
  const dateNice = new Date(a.date + 'T00:00:00Z').toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' });
  const langBlock = (lang, html) => `<div data-lang="${lang}"${lang === 'zh' ? ' hidden' : ''}>${linkifyBrands(html, lang)}</div>`;
  const sources = extractSources(a.html_en);
  return `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow"><span data-lang="en">${a.tag_en || 'Daily Briefing'} · ${dateNice}</span><span data-lang="zh" hidden>${a.tag_zh || '每日简报'} · ${a.date}</span></div>
      <h1 class="page-title"><span data-lang="en">${a.title_en}</span><span data-lang="zh" hidden>${a.title_zh || a.title_en}</span></h1>
      <p class="page-deck"><span data-lang="en">${a.excerpt_en || ''}</span><span data-lang="zh" hidden>${a.excerpt_zh || ''}</span></p>
    </div>
  </section>
  <section style="padding-top:0;">
    <div class="container" style="max-width:820px;">
      ${bylineHTML(dateNice, a.date)}
      <article class="article-body" style="font-size:16px;line-height:1.8;">
        ${langBlock('en', a.html_en)}
        ${langBlock('zh', a.html_zh || a.html_en)}
      </article>
      ${sourcesBlockHTML(sources)}
      <p style="margin-top:32px;"><a href="/news" style="color:var(--accent);font-family:var(--mono);font-size:13px;">← All news</a></p>
    </div>
  </section>`;
}

function articleImage(a) {
  const text = `${a.title_en || ''} ${a.excerpt_en || ''} ${a.title_zh || ''} ${a.excerpt_zh || ''}`.toLowerCase();
  const brand = SITE_DATA.brands.find(b =>
    text.includes(String(b.name).toLowerCase()) || (b.cn && text.includes(String(b.cn).toLowerCase())));
  if (brand && brand.image) return brand.image;
  if (/\bev\b|electric|battery|batteries|phev|hybrid/i.test(text)) return 'images/byd-seal.jpg';
  if (/africa|pickup|commercial/i.test(text)) return 'images/chery-brand.jpg';
  if (/middle east|gulf|saudi|uae|dubai/i.test(text)) return 'images/yangwang-u8.jpg';
  if (/europe|tariff/i.test(text)) return 'images/mg-mg4.jpg';
  return DEFAULT_OG_IMAGE;
}

function articleJsonLd(a) {
  const image = articleImage(a);
  return `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "NewsArticle",
  "headline": ${JSON.stringify(a.title_en)},
  "description": ${JSON.stringify(a.excerpt_en || a.title_en)},
  "datePublished": "${a.date}",
  "dateModified": "${a.date}",
  "image": "${assetUrl(image)}",
  "inLanguage": ["en", "zh-CN"],
  "mainEntityOfPage": "${SITE}/news/${a.slug}",
  "author": {"@type": "Organization", "name": "TopChinaCar", "url": "${SITE}/"},
  "publisher": {"@id": "${SITE}/#organization"}
}
</script>`;
}

for (const a of articles) {
  const route = `/news/${a.slug}`;
  const main = articleMain(a);
  const html = pageHTML(route, {
    title: `${a.title_en} | TopChinaCar`,
    desc: (a.excerpt_en || a.title_en),
    image: articleImage(a),
    ogType: 'article',
    published: a.date
  }, main).replace('</head>', articleJsonLd(a) + '\n</head>');
  fs.writeFileSync(path.join(NEWS_OUT, `${a.slug}.html`), html);
  writeZh(`news/${a.slug}.html`, zhChrome(pageHTML(route, {
    title: `${a.title_zh || a.title_en} | TopChinaCar`,
    desc: (a.excerpt_zh || a.excerpt_en || a.title_zh || a.title_en),
    image: articleImage(a),
    ogType: 'article',
    published: a.date
  }, main, { zh: true }).replace('</head>', articleJsonLd(a) + '\n</head>')));
}
if (articles.length) console.log(`✓ ${articles.length} article page(s) → news/ + zh/news/`);

// ---- 404 ----
const notFoundMain = `
  <section class="page-header">
    <div class="container">
      <div class="section-eyebrow">404</div>
      <h1 class="page-title">Page not found</h1>
      <p class="page-deck">The page you are looking for does not exist. <a href="/" style="color:var(--accent);">Back to the homepage</a> · <a href="/chinese-car-brands" style="color:var(--accent);">Brand Index</a> · <a href="/news" style="color:var(--accent);">News</a></p>
    </div>
  </section>`;
fs.writeFileSync(path.join(ROOT, '404.html'),
  pageHTML('/', { title: 'Page Not Found | TopChinaCar', desc: 'The page you are looking for does not exist.' }, notFoundMain, { noAlt: true }));
console.log('✓ 404.html');

// ---- sitemap.xml ----
function safeDate(date) {
  if (!date) return TODAY;
  return date > TODAY ? TODAY : date;
}

const staticUrls = Object.keys(PAGES).map(r =>
  PAGES[r].robots && PAGES[r].robots.includes('noindex')
    ? null
    : `  <url><loc>${r === '/' ? SITE + '/' : SITE + r}</loc><lastmod>${TODAY}</lastmod></url>`
).filter(Boolean);
const brandUrls = SITE_DATA.brands.map(b =>
  `  <url><loc>${SITE}/chinese-car-brands/${b.id}</loc><lastmod>${TODAY}</lastmod></url>`);
const modelUrls = SITE_DATA.models.filter(m => m.id).map(m =>
  `  <url><loc>${SITE}/models/${m.id}</loc><lastmod>${TODAY}</lastmod></url>`);
const storyUrls = SITE_STORIES
  .filter(s => (SITE_DATA.features || []).some(f => f.slug === s.slug))
  .map(s => `  <url><loc>${SITE}/stories/${s.slug}</loc><lastmod>${safeDate(s.date)}</lastmod></url>`);
const articleUrls = articles.map(a =>
  `  <url><loc>${SITE}/news/${a.slug}</loc><lastmod>${safeDate(a.date)}</lastmod></url>`);
const sectionUrls = SECTIONS.map(s =>
  `  <url><loc>${SITE}${s.route}</loc><lastmod>${TODAY}</lastmod></url>`);
const marketUrls = MARKETS.map(mk =>
  `  <url><loc>${SITE}/markets/${mk.slug}</loc><lastmod>${TODAY}</lastmod></url>`);
const enUrlLines = staticUrls.concat(sectionUrls, marketUrls, brandUrls, modelUrls, storyUrls, articleUrls);
const zhUrlLines = enUrlLines.map(l =>
  l.includes(`<loc>${SITE}/</loc>`)
    ? l.replace(`<loc>${SITE}/</loc>`, `<loc>${SITE}/zh/</loc>`)
    : l.replace(`<loc>${SITE}/`, `<loc>${SITE}/zh/`));
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${enUrlLines.concat(zhUrlLines).join('\n')}
</urlset>
`;
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);
console.log('✓ sitemap.xml');

const recentNews = articles
  .filter(a => safeDate(a.date) >= new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10))
  .slice(0, 1000);
const newsSitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">
${recentNews.map(a => `  <url>
    <loc>${SITE}/news/${a.slug}</loc>
    <news:news>
      <news:publication>
        <news:name>TopChinaCar</news:name>
        <news:language>en</news:language>
      </news:publication>
      <news:publication_date>${safeDate(a.date)}</news:publication_date>
      <news:title>${escAttr(a.title_en)}</news:title>
    </news:news>
  </url>`).join('\n')}
</urlset>
`;
fs.writeFileSync(path.join(ROOT, 'news-sitemap.xml'), newsSitemap);
console.log('✓ news-sitemap.xml');

console.log(`\nDone — ${count} pages + 404 + sitemap.`);
